#!/bin/sh -e

. sh-functions
. guess-functions

iface="${GUESS_NET_IFACE-}"

if [ -n "$iface" ]; then
	guess_device "/class/net/$iface"
	exit 0
fi

for iface in "$SYSFS_PATH"/class/net/*; do
	guess_device "${iface#$SYSFS_PATH}"
done
