#!/bin/sh

. /.initrd/initenv
. uevent-sh-functions

[ -n "$NFSROOT" ] || [ "$ROOT" != '/dev/nfs' ] ||
	NFSROOT='auto'

[ -n "$NFSROOT" ] ||
	exit 0

event="$(make_event)"
environ -q > "$event"
release_event nfsroot "$event"
