#!/bin/bash
### BEGIN INIT INFO
# Provides:            service4
# Required-Start:      service3
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:       3 4 5
# Default-Stop:
### END INIT INFO
