#!/bin/sh -efu

. shell-error

export verbose="${VERBOSE:+-v}"

modules_verbosity() {
	if [ -n "$verbose" ]; then
		while read mod; do
			printf '%s\n' "$mod" >&2
			printf '%s\n' "$mod"
		done
	else
		cat
	fi
}

get_modules() {
	local sysfs_path
	sysfs_path="$1"; shift
	verbose "sysfs: $sysfs_path"
	/sbin/modprobe -q --set-version="$kernel" --show-depends --ignore-all-commands "$1" |
		cut -d' ' -f2 |
		modules_verbosity
}

process_modalias() {
	[ -f "$1"/modalias ] || return 0
	local modalias
	read modalias < "$1"/modalias
	get_modules "$1" "$modalias"
}

process_raid() {
	[ -d "$1"/md ] ||
		return 0

	local level
	read level < "$1"/md/level

	case "$level" in
		raid4|raid5|raid6)
			get_modules "$1" "raid456"
			;;
		*)
			get_modules "$1" "$level"
			;;
	esac
}

process_device() {
	local device
	device="$(readlink -ev "$1" 2>/dev/null)" ||
		return 0

	process_raid "$device"

	process_modalias "$device"

	[ -z "${device##/sys/devices/*}" ] ||
		return 0

	if [ -d "$device/slaves" ]; then
		local slave
		for slave in "$device/slaves"/*; do
			[ ! -e "$slave" ] ||
				process_device "$device/slaves/${slave##*/}"
		done
	fi
	process_device "$device/.."
}
