#!/bin/bash -eu

cwd="${0%/*}"

. "$cwd"/../../../../testing/tests/guess-rootfs-sh-functions

export GUESS_SUFFIX=add:guess-root
export TEST_GUESS_ACTIONS="guess/root/action guess-config"

export RESOLVE_MODALIAS=
export KERNEL_CONFIG=/dev/null

export MAKE_INITRD_TRACE=1
export MAKE_INITRD_TRACE_PIDS=
export MAKE_INITRD_TRACE_EXECUTE_PATTERNS='guess/root/action'
export MAKE_INITRD_TRACE_SRC_PATTERNS='features/rootfs/guess/fstype guess/root/action'
export MAKE_INITRD_TRACE_RUN_PATTERNS='features/rootfs/guess/fstype guess/root/action'

guess_rootfs_run_test "$cwd/rootfs.tar.xz"
