#!/bin/sh -eu

# Reopen std. streams
exec </dev/console >/dev/console 2>&1

# Read initramfs env
. /.initrd/initenv

# Read init incoming arguments
read initargs </.initrd/initargs

# Run system init with arguments. Goodbye!
exec run-init -e /.initrd/kernenv "$rootmnt" "$INIT" $initargs
