#!/bin/sh -eu

# Umount procfs
umount -fl /proc

# Read initramfs env
. /.initrd/initenv

# Read init incoming arguments
read -r initargs </.initrd/initargs

# Run system init with arguments. Goodbye!
exec runas /sbin/init /bin/run-init -e /.initrd/kernenv "$rootmnt" "$INIT" $initargs
