#!/bin/bash -eu

. shell-error
. shell-signal

. /.initrd/initenv
. uevent-sh-functions

message_time=1
pidfile="/var/run/$PROG.pid"
logfile="/var/log/$PROG.log"

exit_handler()
{
	local rc="$?"
	trap - EXIT
	rm -f -- "$pidfile"
	exit $rc
}

[ "${RDLOG-}" != 'console' ] ||
	logfile=/dev/console

[ ! -f "$pidfile" ] ||
	fatal "already running"

set_cleanup_handler exit_handler
echo "$$" >"$pidfile"

exec >"$logfile" 2>&1
message "Starting server ..."

while [ -f "$pidfile" ]; do
	for fn in "$extendir"/*; do
		[ -x "$fn" ] || continue
		name="${fn##*/}"
		name="${name#[0-9][0-9][0-9]-}"

		message "Running $name extender ..."
		"$fn" || message "Extender failed: $name"
	done

	process-boot-method
	sleep 1
done
