#!/bin/sh -eu

. shell-error
. shell-process

daemon_log_file="/var/log/$PROG.out.log"
daemon_err_file="/var/log/$PROG.err.log"
daemon_pid_file="/var/run/$PROG.pid"

if [ "$#" = 0 ]; then
	daemon ||
		exit 1
	message_syslog=1
fi

. /.initrd/initenv
. uevent-sh-functions

glob() { [ -e "$1" ]; }

message "STARTING ..."

while :; do
	# Wait udev event queue
	if ! glob "$filterdir"/*; then
		sleep 0.5
		continue
	fi

	mv -f -- "$filterdir"/* "$eventdir"/ 2>/dev/null ||:

	for handler in "$handlerdir"/*; do
		[ -x "$handler" ] ||
			break

		name="${handler##*/}"
		name="${name#[0-9][0-9][0-9]-}"

		glob "$eventdir/$name".* ||
			continue

		verbose "Running $name handler ..."
		"$handler" || fatal "Event handler failed: $name"
	done

	for ext in "$extendir"/*; do
		[ -x "$ext" ] ||
			break
		name="${ext##*/}"
		name="${name#[0-9][0-9][0-9]-}"

		verbose "Running $name extender ..."
		"$ext" || fatal "Extender failed: $name"
	done
done
