#!/bin/sh

dsort()
{
	local __list=
	__cmp()
	{
		local a="$1" b="$2"
		[ -z "${a##$b/*}" -o ${#a} -ge ${#b} ]
	}
	__sort()
	{
		local n=$# i j a b
		shift

		i=0
		while [ $# -gt 0 ]; do
			eval "local a$i=\"\$1\""
			i=$(($i+1))
			shift
		done

		j=0
		while [ $j -lt $(($n-2)) ]; do
			i=0
			while [ $i -lt $(($n-1-$j)) ]; do
				eval "a=\"\$a$i\"; b=\"\$a$(($i+1))\""
				__cmp "$a" "$b" ||
					eval "a$i=\"\$b\"; a$(($i+1))=\"\$a\""
				i=$(($i+1))
			done
			j=$(($j+1))
		done

		i=0
		while [ $i -lt $n ]; do
			eval "__list=\"\$__list\$a$i \""
			i=$(($i+1))
		done
		unset __sort __cmp
	}
	__sort "$@"
	eval "$1=\"\$__list\""
}
