#!/bin/sh
### BEGIN INIT INFO
# Provides:            localnet
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:       3 4 5
# Default-Stop:
# Short-Description:   Starts the local network.
# Description:         Sets the hostname of the machine and starts the
#                      loopback interface.
# X-LFS-Provided-By:   LFS
### END INIT INFO

. /etc/init.d/template

LOCKFILE=/var/lock/subsys/network

start() {
	action 'Starting lo interface:' ipconfig -q 127.0.0.1:::::lo:none
}

stop() {
	action 'Stoping lo interface:' ipconfig -D lo
}

switch "${1-}"
