#!/bin/sh
### BEGIN INIT INFO
# Provides:            modules
# Required-Start:      sysctl cmdline
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:       3 4 5
# Default-Stop:
# Short-Description:   Loads required modules.
# Description:         Loads modules for PRELOAD.
### END INIT INFO

[ "$1" = start ] || exit 0

. /.initrd/initenv

[ -n "${RD_PRELOAD_MODULES-}" ] ||
	exit 0

. /etc/init.d/functions

preload_modules()
{
	local conf modname rc=0
	for conf in /etc/modules-load.d/*.conf /run/modules-load.d/*.conf /lib/modules-load.d/*.conf /etc/initrd/modules-preudev; do
		# shellcheck disable=SC2162
		[ ! -e "$conf" ] ||
		while read modname; do
			[ -z "${modname##\#*}" ] || modprobe $modname || rc=1
		done < "$conf"
	done 2>"/var/log/preload-modules.log"
	return $rc
}

action_shell 'Loading modules:' preload_modules
