#!/bin/sh
### BEGIN INIT INFO
# Provides:            modules
# Required-Start:      sysctl cmdline
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:       3 4 5
# Default-Stop:
# Short-Description:   Loads required modules.
# Description:         Loads modules for PRELOAD.
### END INIT INFO

[ "$1" = start ] || exit 0

. /.initrd/initenv

[ -z "${NOMODULES-}" ] ||
	exit 0

. /etc/init.d/functions

[ ! -x /sbin/systemd-modules-load ] ||
	action 'Loading modules:' systemd-modules-load
