#!/bin/sh
#
# Copyright (C) 2002 Ivan Zakharyaschev <imz@altlinux.ru>.
# Copyright (C) 2002,2003 Dmitry V. Levin <ldv@altlinux.org>.
#
# Output formatting functions.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

# Offset from right margin of the screen to start status labels at.
: ${RES_OFFSET:=8}
[ -n "$RES_OFFSET" ] && [ "$RES_OFFSET" -gt 0 ] 2>/dev/null || RES_OFFSET=8

# Terminal sequence to move to that position.
MOVE_TO_COL()
{
	[ -n "${COLUMNS-}" ] || COLUMNS=80
	local pos=$(($COLUMNS - $RES_OFFSET))
	[ $pos -le 0 ] ||
		printf "\033[%dG" $pos # Horizontal Position Absolute.
}

# Enumerate colors
: ${BLACK:=0} ${RED:=1} ${GREEN:=2} ${YELLOW:=3} ${BLUE:=4} ${MAGENTA:=5} ${CYAN:=6} ${WHITE:=7}

SETCOLOR_SUCCESS() { printf "\033[1m\033[3%dm" $GREEN;          } # Set 'success' color (currently: green)
SETCOLOR_FAILURE() { printf "\033[1m\033[3%dm" $RED;            } # Set 'failure' color (currently: red)
SETCOLOR_WARNING() { printf "\033[1m\033[3%dm" $YELLOW;         } # Set 'warning' color (currently: yellow)
SETCOLOR_INFO()    { printf "\033[1m\033[36m"  $CYAN;           } # Set 'info' color (currently: cyan)
SETCOLOR_BANNER()  { printf "\033[3%dm\033[4%dm" $BLUE $YELLOW; } # Set 'banner' color (currently: blue on yellow)
SETCOLOR_NORMAL()  { printf "\033[39;49m\033[0;10m";            } # Terminal sequence to reset to the default color.
