#!/bin/bash
# Copyright (C) 2002 Ivan Zakharyaschev <imz@altlinux.ru>.
# Copyright (C) 2002,2003 Dmitry V. Levin <ldv@altlinux.org>.

# Offset from right margin of the screen to start status labels at.
[ -n "${RES_OFFSET-}" ] && [ "$RES_OFFSET" -gt 0 ] 2>/dev/null || RES_OFFSET=8

# Terminal sequence to move to that position.
TO_COL=$(pos=$((${COLUMNS:-80} - $RES_OFFSET)); [ $pos -le 0 ] || printf "\033[%dG" $pos;)

# Enumerate colors
: "${BLACK:=0}" "${RED:=1}" "${GREEN:=2}" "${YELLOW:=3}" "${BLUE:=4}" "${MAGENTA:=5}" "${CYAN:=6}" "${WHITE:=7}"

COLOR_SUCCESS=$(printf "\033[1m\033[3%dm" $GREEN)
COLOR_FAILURE=$(printf "\033[1m\033[3%dm" $RED)
COLOR_WARNING=$(printf "\033[1m\033[3%dm" $YELLOW)
COLOR_INFO=$(printf "\033[1m\033[3%dm" $CYAN)
COLOR_BANNER=$(printf "\033[3%dm\033[4%dm" $BLUE $YELLOW)
COLOR_NORMAL=$(printf "\033[39;49m\033[0;10m")
