#!/bin/bash
### BEGIN INIT INFO
# Provides:            poll
# Required-Start:      cmdline mountvirtfs
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:       3 4 5
# Default-Stop:
# Short-Description:   The process for periodically starting scripts.
# Description:         The process for periodically starting scripts.
# X-LFS-Provided-By:   LFS
### END INIT INFO

. /.initrd/initenv
. /etc/init.d/template
. uevent-sh-functions

start()
{
	rmdir -- "$uevent_confdb/queue/pause/poll" 2>/dev/null ||:

	mkdir -p -- /.initrd/uevent/queues/poll/.tmp
	event="$(make_event poll)"
	release_event "periodically" "$event"

	return 0
}

stop()
{
	mkdir -p -- "$uevent_confdb/queue/pause/poll"
	return 0
}

switch "${1-}"
