#!/bin/sh
### BEGIN INIT INFO
# Provides:            runinit
# Required-Start:      killall
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:       2
# Default-Stop:
# Short-Description:   Tells init to start real init.
# Description:         Tells init to start real init.
### END INIT INFO

[ "$1" = start ] || exit 0

. /.initrd/initenv
. /etc/init.d/functions

echo "Running init ($INIT)"

read initargs </.initrd/initargs
printf '"%s" "%s" %s\n' "$rootmnt" "$INIT" "$initargs" >> /sbin/init
exec telinit u
