#!/bin/bash
### BEGIN INIT INFO
# Provides:            shell
# Required-Start:
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:       3 4 5
# Default-Stop:
# Short-Description:   Runs emergency shell
# Description:         Runs emergency shell
### END INIT INFO

. /.initrd/initenv
. /etc/init.d/template

export RDSHELL_FOREVER=1

NAME=rdshell
ARGS="--lockfile $LOCKFILE --pidfile /var/run/$NAME.pid --name $NAME --displayname shell"

start()
{
	start_daemon $ARGS --background "$NAME"
	RETVAL=$?
	return $RETVAL
}

stop() {
	stop_daemon $ARGS -- "$NAME"
	RETVAL=$?
	return $RETVAL
}

switch "${1-}"
