#!/bin/sh
### BEGIN INIT INFO
# Provides:            timer
# Required-Start:      cmdline
# Should-Start:
# Required-Stop:       uevent
# Should-Stop:
# Default-Start:       3 4 5
# Default-Stop:
# Short-Description:   Runs user-specified programs at periodic scheduled times.
# Description:         Runs user-specified programs at periodic scheduled times.
### END INIT INFO

. /etc/init.d/template

NAME=timerd
PIDFILE=/var/run/$NAME.pid
ARGS="--lockfile $LOCKFILE --pidfile $PIDFILE --displayname $NAME"

pre_start()
{
	(
		. /.initrd/initenv
		printf 'period=%s repeat=1\t/lib/shell/rootdelay\n' "${ROOTDELAY:-180}" 
	) > /etc/timer.d/rootdelay.conf
}

start() {
	pre_start
	start_daemon $ARGS -- $NAME || RETVAL=$?
	return $RETVAL
}

stop() {
	stop_daemon $ARGS -- /bin/sh -eu /sbin/$NAME || RETVAL=$?
	return $RETVAL
}

switch "${1-}"
