#!/bin/sh
### BEGIN INIT INFO
# Provides:            uevent
# Required-Start:      cmdline
# Should-Start:        $syslog
# Required-Stop:
# Should-Stop:
# Default-Start:       3 4 5
# Default-Stop:
# Short-Description:   Process kernel events.
# Description:         Processing kernel events.
### END INIT INFO

. /etc/init.d/template
. uevent-sh-functions

NAME=ueventd
PIDFILE=/var/run/$NAME.pid
ARGS="--lockfile $LOCKFILE --pidfile "$PIDFILE""

start() {
	start_daemon $ARGS -- \
		"$NAME" \
		    --pidfile "$PIDFILE" \
		    --logfile "/var/log/$NAME.log" \
		    "$filterdir" /sbin/uevent-handler
	RETVAL=$?
	return $RETVAL
}

stop() {
	stop_daemon $ARGS -- "$NAME"
	RETVAL=$?
	return $RETVAL
}

switch "${1-}"
