#!/bin/sh
### BEGIN INIT INFO
# Provides:            uevent
# Required-Start:      udev
# Should-Start:
# Required-Stop:       udev
# Should-Stop:
# Default-Start:       3 4 5
# Default-Stop:
# Short-Description:   Process kernel events.
# Description:         Processing kernel events.
### END INIT INFO

. /etc/init.d/template

NAME=ueventd
PIDFILE=/var/run/$NAME.pid
ARGS="--lockfile $LOCKFILE --pidfile $PIDFILE --displayname $NAME"

start() {
	start_daemon $ARGS -- $NAME || RETVAL=$?
	return $RETVAL
}

stop() {
	stop_daemon $ARGS -- /bin/sh -eu /sbin/$NAME || RETVAL=$?
	return $RETVAL
}

switch "${1-}"
