#!/bin/bash -efu
# SPDX-License-Identifier: GPL-3.0-or-later

. guess-functions

$TRACE_SOURCE "Processing ..."

is_active_feature "sshfsroot" ||
	exit 0

[ -n "${SSHFS_CONFIG-}" ] && [ -z "${SMART_CARD_PKCS11_MODULE-}" ] ||
	exit 0

readarray -t SSHFS_PKCS11_MODULES < <(sed -n -e 's/^[[:space:]]*PKCS11Provider[[:space:]]\+//p' "$SSHFS_CONFIG" |sort -u)

case "${#SSHFS_PKCS11_MODULES[@]}" in
	0)
		;;
	1)
		guess_feature "smart-card"
		guess_variable "SMART_CARD_PKCS11_MODULE" "${SSHFS_PKCS11_MODULES[0]}"
		;;
	*)
		fatal  "Different PKCS11 providers are not supported for sshfsroot"
		;;
esac
