#!/bin/bash -efu

cwd="${0%/*}"

. "$cwd"/../../../../testing/tests/guess-feature-sh-functions

guess_feature_test_init "$0"

mkdir -p -- "$SYSFS_PATH/devices/test-mpath/dm"
printf '%s\n' 'mpath-test' > "$SYSFS_PATH/devices/test-mpath/dm/uuid"

features/multipath/guess/device /devices/test-mpath
guess_feature_test_dump
