#!/bin/sh

. /.initrd/initenv
. uevent-sh-functions
. initrd-sh-functions
. rdshell-sh-functions

freekey() {
	local d="/mnt/luks-key"
	[ -d "$d" ] && umount "$d" && rmdir "$d" ||:
}

findkey() {
	local path keydev luksdev mnt="/mnt/luks-key"

	[ -f /etc/luks.keys ] ||
		exit 2

	while IFS='	' read path keydev luksdev; do
		if [ -n "$luksdev" ]; then
			get_dev "$luksdev" ||
				continue
		fi

		mnt=
		if [ -n "$keydev" ]; then
			mkdir -p -- "$mnt"
			mount -r "$keydev" "$mnt" ||
				exit 1
		fi

		if [ ! -f "$mnt/$path" ]; then
			error "luks: $path: keyfile not found."
			exit 1
		fi

		keyfile="$mnt/$path"
		verbose "Keyfile '$path' for '${LUKS_ROOT#/dev/}' encrypted partition."
		return 0

	done < /etc/luks.keys

	# Keyfile not found yet.
	exit 2
}

readkey() {
	local keyfile="$1"
	[ -s "$keyfile" ] ||
		return 0
	if [ -z "${keyfile##*.gpg}" ]; then
		gpg --quiet --decrypt "$keyfile"
		return
	fi
	cat "$keyfile"
}

handler() {
	nameluks="${LUKS_ROOT##*/}-luks"

	# skip if $nameluks has already exist
	! dmsetup info "$nameluks" >/dev/null 2>&1 ||
		exit 0

	local rc=0 keyfile=
	if [ -n "${LUKS_KEY-}" ]; then
		findkey ||
			rc="$?"
		[ "$rc" != 0 ] ||
			{ readkey "$keyfile" |cryptsetup -d- luksOpen "$LUKS_ROOT" "$nameluks"; } ||
			rc="$?"
		freekey
	else
		# WARNING: Wait decrypt forever!
		rc=2
		while [ "$rc" = 2 ]; do
			cryptsetup luksOpen "$LUKS_ROOT" "$nameluks"
			rc="$?"
		done
	fi

	if [ "$rc" != 0 ]; then
		printf 'ERROR: %s: unable to activate LUKS (rc=%s)\n' "$LUKS_ROOT" "$rc" >&2
		exit 1
	fi
}

while ! console_lock; do
	sleep 0.5
done

exec 0</dev/console >/dev/console 2>&1

rc=0
for e in "$eventdir"/luks.*; do
	r=0
	( . "$e"; handler; ) || r="$?"
	case "$r" in
		2) ;;
		1) rc=1 ;;
		0) done_event "$e" ;;
	esac
done

console_unlock
exit $rc
