#!/bin/bash -efu

. guess-functions
. shell-error
. shell-quote

RULES=()
VARS=()

remember_var()
{
	local v
	for v in "${VARS[@]}"; do
		[ "$v" != "$1" ] || return 0
	done
	VARS+=("$1")
}

append_word()
{
	local retval="$1"; shift
	eval "$retval=\"\${$retval:+\$$retval }$*\""
	eval "export $retval"
}

remove_word()
{
	local retval="$1"; shift
	local word="$1"; shift
	local arr i

	eval "arr=\"\$$retval\""
	set -- $arr

	i="$#"
	while [ "$i" != 0 ]; do
		[ "$1" = "$word" ] || set -- "$@" "$1"
		shift
		i=$(($i - 1))
	done

	eval "$retval=\"\$*\""
	eval "export $retval"
}

check_variable()
{
	eval "local var=\"\${$1-}\""

	case "$2" in
		'!=')
			test "$var" != "$3"
			;;
		'==')
			test "$var" = "$3"
			;;
		'+=')
			append_word "$1" "$3"
			remember_var "$1"
			;;
		'-=')
			remove_word "$1" "$3"
			remember_var "$1"
			;;
		'=')
			eval "$1=\"\$3\""
			eval "export $1"
			remember_var "$1"
			;;
		*)
			fatal "unknown operator $rule_name (word=$n_word): $2"
			return 1
			;;
	esac
}

check_existence()
{
	local op expect=0 ret=0

	case "${1,,}" in
		1|yes|true) expect=0 ;;
		0|no|false) expect=1 ;;
		*) fatal "unknown value: $rule_name (word=$n_word): $1" ;;
	esac
	shift

	case "$1" in
		'!=') op='-ne' ;;
		'==') op='-eq' ;;
		*) fatal "unknown operation: $rule_name (word=$n_word): $1" ;;
	esac
	shift

	test -e "$1" || ret=1
	test "$ret" "$op" "$expect"
}

check_contains()
{
	local arr e
	eval "arr=\"\${$1-}\""
	for e in $arr; do
		[ "$e" != "$2" ] || return 0
	done
	return 1
}

check_kconfig()
{
	local val='' not='' op=''

	[ -e "$KERNEL_CONFIG" ] ||
		return 1

	case "${3,,}" in
		y|builtin) val="(y)"   not=0 ;;
		m|module)  val="(m)"   not=0 ;;
		enabled)   val="(m|y)" not=0 ;;
		disabled)  val="(m|y)" not=1 ;;
		*) fatal "unknown value: $rule_name (word=$n_word): $3" ;;
	esac

	case "$2" in
		'!=') op='-ne' ;;
		'==') op='-eq' ;;
		*) fatal "unknown operation: $rule_name (word=$n_word): $2" ;;
	esac

	local ret=0
	grep -E -qs "^CONFIG_$1=$val\$" "$KERNEL_CONFIG" || ret=1

	case "$not:$ret" in
		1:0) ret=1 ;;
		1:1) ret=0 ;;
	esac

	test "$ret" "$op" 0
}

check_kmodule()
{
	local val='' not='' op=''

	case "${3,,}" in
		y|builtin) val="builtin"          not=0 ;;
		m|module)  val="module"           not=0 ;;
		enabled)   val="(builtin|module)" not=0 ;;
		disabled)  val="(builtin|module)" not=1 ;;
		*) fatal "unknown value: $rule_name (word=$n_word): $3" ;;
	esac

	case "$2" in
		'!=') op='-ne' ;;
		'==') op='-eq' ;;
		*) fatal "unknown operation: $rule_name (word=$n_word): $2" ;;
	esac

	local ret=0
	depinfo ${KERNEL:+-k "$KERNEL"} --no-deps --no-firmware "$1" 2>/dev/null |
		grep -E -qs "^$val " ||
		ret=1

	case "$not:$ret" in
		1:0) ret=1 ;;
		1:1) ret=0 ;;
	esac

	test "$ret" "$op" 0
}

action()
{
	case "${1,,}" in
		run)
			"$3" || return
			;;
	esac
}

parse_expression()
{
	case "${1,,}" in
		var)
			check_variable  "$2" "$4" "$5" ||
				return
			;;
		exists)
			check_existence "${5:-true}" "${4:-==}" "$2" ||
				return
			;;
		contains)
			check_contains  "$2" "$3" ||
				return
			;;
		kconfig)
			check_kconfig "$2" "${3:-==}" "${4:-enabled}" ||
				return
			;;
		kmodule)
			check_kmodule "$2" "${3:-==}" "${4:-enabled}" ||
				return
			;;
		action)
			action "$2" "$4" "$5" ||
				return
			;;
		*)
			message "unknown keyword: $rule_name (word=$n_word): $1"
			;;
	esac
}

parse_rules()
{
	local arg rule rule_name rule_word n_word

	for rule in "${RULES[@]}"; do
		export GUESS_SUFFIX='add:guess-v1'

		n_word=0
		rule_name="${rule%%=*}"

		quote_shell_args arg "${rule#*=}"
		eval "local rule=$arg"
		set -- $rule

		for rule_word; do
			[ -n "$rule_word" ] ||
				continue

			n_word=$(($n_word + 1))

			shopt -s nocasematch

			if [[ "$rule_word" =~ CONTAINS\{([^,}]+),([^,}]+)\} ]]; then
				shopt -u nocasematch
				parse_expression "contains" "${BASH_REMATCH[1]}" "${BASH_REMATCH[2]}" ||
					continue 2
			elif [[ "$rule_word" =~ KCONFIG\{([^,}]+)\}((\!=|==)(m|module|y|builtin|enabled|disabled))? ]]; then
				shopt -u nocasematch
				parse_expression "kconfig" "${BASH_REMATCH[1]}" "${BASH_REMATCH[3]}" "${BASH_REMATCH[4]}" ||
					continue 2
			elif [[ "$rule_word" =~ KMODULE\{([^,}]+)\}((\!=|==)(m|module|y|builtin|enabled|disabled))? ]]; then
				shopt -u nocasematch
				parse_expression "kmodule" "${BASH_REMATCH[1]}" "${BASH_REMATCH[3]}" "${BASH_REMATCH[4]}" ||
					continue 2
			elif [[ "$rule_word" =~ (ACTION|CONTAINS|EXISTS|VAR)\{([^}]+)\}((\!=|==|\+=|\-=|=)(.*))? ]]; then
				shopt -u nocasematch
				parse_expression "${BASH_REMATCH[1]}" "${BASH_REMATCH[2]}" "" \
					         "${BASH_REMATCH[4]}" "${BASH_REMATCH[5]}" ||
					continue 2
			else
				shopt -u nocasematch
				fatal "unknown expression: $rule_name (word=$n_word): $rule_word"
			fi
		done
		echo "GUESS_RULE: $rule"
	done
}

readarray -t RULES < <(set |grep -E '^GUESSv1_[^=]+_RULE=') ||:

[ "${#RULES[@]}" -gt 0 ] ||
	exit 0

parse_rules

GUESS_SUFFIX='add:guess-v1'

for v in "${VARS[@]}"; do
	case "$v" in
		FEATURES)
			eval "arr=\"\${$v-}\""
			for n in $arr; do
				guess_feature "$n"
			done
			;;
		MODULES)
			eval "arr=\"\${$v-}\""
			for n in $arr; do
				guess_module "$n"
			done
			;;
		*)
			eval "guess_variable \"$v\" \"\${$v-}\""
			;;
	esac
done
