#!/bin/bash -eu

cwd="${0%/*}"

. data/bin/shell-locks

show_self_locks()
{
	grep -E -o -e "^lock:.* FLOCK .* (READ|WRITE) " "/proc/self/fdinfo"/* 2>/dev/null ||:
}

fd_lock 91 "$cwd/lock-1"
fd_lock 91 "$cwd/lock-2"
fd_lock 91 "$cwd/lock-3"

echo === step 1 ===
show_self_locks

fd_lock 91 "$cwd/lock-1"
fd_lock 91 "$cwd/lock-1"
fd_lock 91 "$cwd/lock-1"

echo === step 2 ===
show_self_locks

