#!/bin/sh -eu

. sh-functions
. guess-functions

export LIBMOUNT_FSTAB="${FSTAB:-/etc/fstab}"
export LIBMOUNT_MTAB="${PROC_MOUNTS:-$PROCFS_PATH/mounts}"

pass=' '
for dir in ${MOUNTPOINTS-}; do
	[ -n "${pass##* $dir *}" ] ||
		continue

	out="$(findmnt -n -o MAJ:MIN,FSTYPE,SOURCE --target "$dir")" ||
		fatal "Unable to find device for '$dir' mount point"

	printf '%s\n' "$out" |
	while read -r majmin fstype device; do
		# kernel >= 2.6.27
		guess_device "/dev/block/$majmin"
		guess_fstype "$device" "$fstype"
	done

	guess_feature rootfs

	pass="$pass$dir "
done
