#!/bin/sh

. /.initrd/initenv
. uevent-sh-functions

[ "${RDMODE-}" = 'live' ] ||
	exit 0

[ -n "${RDLXC-}" ] ||
	exit 0

trim()
{
	printf '%s' "$*"
}

lxc_read_config()
{
	local str cfg name value func eof=

	cfg="$1"; shift
	func="$1"; shift

	while [ -z "$eof" ]; do
		read str || eof=1

		[ -n "${str##\#*}" ] ||
			continue

		name="$(trim ${str%%=*})"
		value="$(trim ${str#*=})"

		"$func" "$name" "$value"
	done < "$cfg"
}

lxc_rootfs=
get_rootfs()
{
	[ "$1" != 'lxc.rootfs' ] ||
		lxc_rootfs="$2"
}

lxc_path="$(lxc-config lxc.lxcpath)"
for dir in "$lxc_path"/*; do
	[ -d "$dir" ] ||
		continue

	lxc_name="${dir##*/}"

	lxc_rootfs=
	lxc_read_config "$dir/config" get_rootfs

	[ ! -e "/var/lock/lxc-spawn/$lxc_name" ] && mountpoint -q "$lxc_rootfs" ||
		continue

	lxc-spawn "$lxc_name" &
done
