#!/bin/bash -efu

cwd="${0%/*}"

. "$cwd"/../../../../testing/tests/guess-feature-sh-functions

guess_feature_test_init "$0"

mkdir -p -- \
	"$SYSFS_PATH/devices/test-nvme" \
	"$SYSFS_PATH/devices/test-parent"
printf '%s\n' 'nvm' > "$SYSFS_PATH/devices/test-parent/subsystype"
printf '%s\n' 'pcie' > "$SYSFS_PATH/devices/test-parent/transport"
printf '%s\n' 'pci:v00008086d0000F1A5' > "$SYSFS_PATH/devices/test-nvme/modalias"
ln -s -- "$SYSFS_PATH/devices/test-nvme" "$SYSFS_PATH/devices/test-parent/nvme0"

features/nvmf/guess/device /devices/test-parent
guess_feature_test_dump
