#!/bin/bash

. shell-error
. /.initrd/initenv

PROG="$QUEUE: session=$SESSION: $PROG"
message_time=1

while [ -z "${eof-}" ]; do
	read -r fsdev fsdir _ ||
		eof=1

	[ -n "$fsdev" ] && [ -d "$fsdir" ] ||
		continue

	if [ -n "${ROOTONLY-}" ]; then
		[ "$fsdir" = "$rootmnt" ] ||
			continue
	fi

	mountpoint -q "$fsdir" ||
		fatal "$fsdir: Not mounted"

done < /etc/fstab
