#!/bin/bash

. shell-error
. /.initrd/initenv

PROG="$QUEUE: session=$SESSION: $PROG"
message_time=1

! chrooted "$rootmnt" test -e "$INIT" ||
	exit 0

msglock="/.initrd/polld/$PROG/message-shown"
deadline='/.initrd/rootdelay/deadline'
consmsg="/.initrd/rootdelay/message"

[ ! -f "$deadline" ] ||
	echo 0 > "$deadline" ||:

[ ! -d "$msglock" ] ||
	exit 1

mkdir -p -- "$msglock" ||:

printf > "$consmsg" '%s\n' \
	"The init program \`$INIT' not found in the root directory."

fatal "it looks like all mountpoints are ready, but \`$INIT' not found" \
      "in the new root directory ($rootmnt)." \
      "There is no point in waiting any longer."
