#!/bin/sh -efu

plymouth_script() {
	[ -z "$NOSPLASH" ] || return 0
	# Run plymouth here if it looks like KMS framebuffer
	[ "${vga%x*}" = "0" ] && return 0

	mkdir -pm 0755 /dev/.systemd
	: > /dev/.systemd/plymouth

	/sbin/plymouthd
	/bin/plymouth --show-splash
}

plymouth_script
