#!/bin/sh -efu

plymouth_script() {
	[ -z "$NOSPLASH" ] || return 0
	# Run plymouth here if it looks like KMS framebuffer
	[ "${vga%x*}" = "0" ] && return 0

	/sbin/plymouthd
	/bin/plymouth --show-splash
}

plymouth_script
