#!/bin/sh -efu

[ ! -d "$TESTDIR/.travis.cmd" ] ||
	exit 0

mkdir -p -- "$TESTDIR/.travis.cmd"

printf '%s\n' "$1" > "$TESTDIR/.travis.cmd/msg"
date +'%s%N'       > "$TESTDIR/.travis.cmd/ts"

printf 'travis_fold:start:%s\r' "$1"
printf 'travis_time:start:ts.%s\r' "$1"
printf '\n'
