#!/bin/sh -efu

[ -d "$TESTDIR/.travis.cmd" ] ||
	exit 0

read -r msg < "$TESTDIR/.travis.cmd/msg" ||:
read -r ts  < "$TESTDIR/.travis.cmd/ts"  ||:

te="$(date +'%s%N')"
duration="$((${te:-0} - ${ts:-0}))"

printf 'travis_time:end:ts.%s:start=%s,finish=%s,duration=%s\r' "$msg" "$ts" "$te" "$duration"
printf 'travis_fold:end:%s\r' "$msg"
printf '\n'

rm -rf -- "$TESTDIR/.travis.cmd"
