# SPDX-License-Identifier: GPL-3.0-or-later

$(call assgin-shell-once,KICKSTART_DIRS,$(FEATURESDIR)/kickstart/bin/get-ks-configs)

FAT_MODULES = fs-vfat /fs/nls/
ZFS_MODULES = zfs

MODULES_ADD += $(LUKS_MODULES) drivers/md/raid
MODULES_TRY_ADD += $(FAT_MODULES)
MODULES_TRY_ADD += $(ZFS_MODULES)

PUT_FEATURE_FILES += $(KICKSTART_FILES)
PUT_FEATURE_DIRS += $(KICKSTART_DATADIR) $(KICKSTART_DIRS)
PUT_FEATURE_PROGS += $(KICKSTART_PROGS)
PUT_FEATURE_PROGS_WILDCARD += $(KICKSTART_PROGS_PATTERNS)
