#!/bin/bash -efu

cwd="${0%/*}"
. "$cwd/../trace-sh-functions"

trace_test_init "$0"
export MAKE_INITRD_TRACE_DEBUG_FILTERS=1
export MAKE_INITRD_TRACE_EXECUTE_PATTERNS='nomatch'
export MAKE_INITRD_TRACE_RUN_PATTERNS='nomatch'

trace_source "Processing ..."

trace_func() {
	trace_enter arg1
	trace_run /bin/echo hello >/dev/null
}

trace_func
