# SPDX-License-Identifier: GPL-3.0-or-later

ifeq ($(INITRD_NO_LIBNSS),)
SYSTEM_GLIBC_LIBNSS_BIN   := $(FEATURESDIR)/system-glibc/bin/system-glibc-libnss

$(call assign-shell-once,SYSTEM_GLIBC_LIBNSS_FILES,$(SYSTEM_GLIBC_LIBNSS_BIN) files)
$(call assign-shell-once,SYSTEM_GLIBC_LIBNSS_DIRS, $(SYSTEM_GLIBC_LIBNSS_BIN) dirs)

PUT_FEATURE_FILES += $(SYSTEM_GLIBC_LIBNSS_FILES)
PUT_FEATURE_DIRS  += $(SYSTEM_GLIBC_LIBNSS_DIRS)
endif

ifeq ($(INITRD_NO_LIBGCC_S),)
SYSTEM_GLIBC_LIBGCC_S_BIN   := $(FEATURESDIR)/system-glibc/bin/system-glibc-libgcc_s

$(call assign-shell-once,SYSTEM_GLIBC_LIBGCC_S_FILES,$(SYSTEM_GLIBC_LIBGCC_S_BIN) files)
$(call assign-shell-once,SYSTEM_GLIBC_LIBGCC_S_DIRS, $(SYSTEM_GLIBC_LIBGCC_S_BIN) dirs)

PUT_FEATURE_FILES += $(SYSTEM_GLIBC_LIBGCC_S_FILES)
PUT_FEATURE_DIRS  += $(SYSTEM_GLIBC_LIBGCC_S_DIRS)
endif

ifeq ($(INITRD_NO_PWGR),)
SYSTEM_GLIBC_PWGR_BIN   := $(FEATURESDIR)/system-glibc/bin/system-glibc-pwgr

$(call assign-shell-once,SYSTEM_GLIBC_PWGR_FILES,$(SYSTEM_GLIBC_PWGR_BIN) files)
$(call assign-shell-once,SYSTEM_GLIBC_PWGR_DIRS, $(SYSTEM_GLIBC_PWGR_BIN) dirs)

PUT_FEATURE_FILES += $(SYSTEM_GLIBC_PWGR_FILES)
PUT_FEATURE_DIRS  += $(SYSTEM_GLIBC_PWGR_DIRS)
endif

ifeq ($(INITRD_NO_NETWORK),)
SYSTEM_GLIBC_NETWORK_BIN   := $(FEATURESDIR)/system-glibc/bin/system-glibc-network

$(call assign-shell-once,SYSTEM_GLIBC_NETWORK_FILES,$(SYSTEM_GLIBC_NETWORK_BIN) files)
$(call assign-shell-once,SYSTEM_GLIBC_NETWORK_DIRS, $(SYSTEM_GLIBC_NETWORK_BIN) dirs)

PUT_FEATURE_FILES += $(SYSTEM_GLIBC_NETWORK_FILES)
PUT_FEATURE_DIRS  += $(SYSTEM_GLIBC_NETWORK_DIRS)
endif
