#!/bin/sh -eu

. sh-functions

kmodules_list="$1"
shift

egrep -qs '^ext4 ' "$kmodules_list" ||
	exit 0

depinfo --set-version="$kernel" -D "ext4" 2>/dev/null | egrep -qs '^module ' ||
	exit 0

add-module 'libcrc32c'
add-module 'crc32c'

egrep '^alias crc32c ' "$kernel_modules_dir"/modules.alias |
while read prefix alias module; do
	add-module "$module"
done
