#!/bin/bash -eu

. /.initrd/initenv
. uevent-sh-functions

PROG="${QUEUE:--}: session=${SESSION:-0}: $PROG"
message_time=1

lvm vgscan >/dev/null
lvm vgchange -ay --noudevsync >/dev/null ||:

for e in "$eventdir"/lvm.*; do
	[ -f "$e" ] || break
	done_event "$e"
done
