#!/bin/sh -eu

. /.initrd/initenv
. uevent-sh-functions

lvm vgscan >/dev/null
lvm vgchange -ay --noudevsync >/dev/null ||:

for e in "$eventdir"/lvm.*; do
	[ -f "$e" ] || break
	done_event "$e"
done
