#!/bin/bash -efu

cwd="${0%/*}"

. "$cwd"/../../../../testing/tests/guess-feature-sh-functions

guess_feature_test_init "$0"

export LOCALES='ru_RU'

features/locales/guess/common
guess_feature_test_dump
