#!/bin/bash -efu
# SPDX-License-Identifier: GPL-3.0-or-later

expect -f- <<EOF
set timeout -1
set send_slow {1 .1}
spawn $*
expect {
	-re "Enter passphrase for /dev/.*: " {
		sleep 1
		send -s -- "qwerty\r"
		exp_continue
	}
	eof exit
}
EOF
