#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-or-later

MAKE_INITRD_PACKAGES="make findutils udev elfutils-libelf kmod-libs zlib bzip2-libs libzstd xz-libs libxcrypt-compat"

MAKE_INITRD_PACKAGES_DEVEL="$MAKE_INITRD_PACKAGES"
MAKE_INITRD_PACKAGES_DEVEL+=" gcc make automake autoconf bison flex"
MAKE_INITRD_PACKAGES_DEVEL+=" kmod-devel zlib-devel bzip2-devel xz-devel libxcrypt-devel"
MAKE_INITRD_PACKAGES_DEVEL+=" libzstd-devel elfutils-libelf-devel libtirpc-devel"

KERNEL_PACKAGES="kernel$KERNEL_FLAVOR"

BOOTLOADER_EFI_PACKAGES="grub2-efi-x64 grub2-efi-x64-modules"
BOOTLOADER_PC_PACKAGES="grub2-pc grub2-pc-modules"

SYSIMAGE_BASE_PACKAGES="$MAKE_INITRD_PACKAGES $KERNEL_PACKAGES systemd"
SYSIMAGE_EXTRA_PACKAGES="pwgen mdadm lvm2 cryptsetup btrfs-progs e2fsprogs xfsprogs dosfstools"

KICKSTART_PACKAGES="$MAKE_INITRD_PACKAGES"
KICKSTART_PACKAGES+=" e2fsprogs btrfs-progs xfsprogs dosfstools cryptsetup lvm2"
KICKSTART_PACKAGES+=" mdadm util-linux rsync wget unzip tar cpio pwgen zstd lz4"

SSH_SERVER_PACKAGES="openssh-server"

ZFS_PACKAGES="unknown-package-for-altlinux"
