#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-or-later

MAKE_INITRD_PACKAGES="make udev libelf libkmod zlib bzlib libzstd liblzma libbpf libjson-c5"

MAKE_INITRD_PACKAGES_DEVEL="$MAKE_INITRD_PACKAGES"
MAKE_INITRD_PACKAGES_DEVEL+=" gcc make automake autoconf bison flex"
MAKE_INITRD_PACKAGES_DEVEL+=" libkmod-devel zlib-devel bzlib-devel liblzma-devel"
MAKE_INITRD_PACKAGES_DEVEL+=" libzstd-devel libelf-devel libtirpc-devel libcrypt-devel"
MAKE_INITRD_PACKAGES_DEVEL+=" libjson-c-devel"

KERNEL_PACKAGES="kernel-latest"

BOOTLOADER_EFI_PACKAGES="grub-common grub-efi"
BOOTLOADER_PC_PACKAGES="grub-common grub-pc"

SYSIMAGE_LOCAL_INIT_PACKAGES="systemd"
SYSIMAGE_NETWORK_INIT_PACKAGES="sysvinit startup"

SYSIMAGE_BASE_PACKAGES="$MAKE_INITRD_PACKAGES mingetty"
SYSIMAGE_EXTRA_PACKAGES="pwgen mdadm lvm2 cryptsetup btrfs-progs e2fsprogs xfsprogs dosfstools reiserfsprogs"

KICKSTART_PACKAGES="$MAKE_INITRD_PACKAGES"
KICKSTART_PACKAGES+=" systemd util-linux rsync wget cryptsetup lvm2 mdadm pwgen"
KICKSTART_PACKAGES+=" e2fsprogs btrfs-progs xfsprogs dosfstools reiserfsprogs"
KICKSTART_PACKAGES+=" sfdisk unzip tar cpio eject lz4 f2fs-tools"

SSH_SERVER_PACKAGES="openssh-server syslogd"

ZFS_PACKAGES="unknown-package-for-altlinux"
