#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-or-later

MAKE_INITRD_PACKAGES="make udev libelf1 libkmod2 zlib1g libbz2-1.0 libzstd1"
MAKE_INITRD_PACKAGES+=" liblzma5 libjson-c5 squashfs-tools"

MAKE_INITRD_PACKAGES_DEVEL="$MAKE_INITRD_PACKAGES bison flex bzip2"
MAKE_INITRD_PACKAGES_DEVEL+=" gcc make automake autoconf pkg-config udev scdoc"
MAKE_INITRD_PACKAGES_DEVEL+=" libkmod-dev libz-dev libbz2-dev liblzma-dev"
MAKE_INITRD_PACKAGES_DEVEL+=" libzstd-dev libelf-dev libtirpc-dev libcrypt-dev"
MAKE_INITRD_PACKAGES_DEVEL+=" libjson-c-dev"

KERNEL_PACKAGES="linux-generic"

INIT_PACKAGES="systemd"
ZFS_PACKAGES="zfsutils-linux"

SYSIMAGE_PACKAGES="$MAKE_INITRD_PACKAGES $INIT_PACKAGES"
SYSIMAGE_PACKAGES+=" pwgen mdadm lvm2 cryptsetup btrfs-progs e2fsprogs xfsprogs dosfstools"
SYSIMAGE_PACKAGES+=" systemd-boot systemd-boot-efi grub-pc"
SYSIMAGE_PACKAGES+=" $ZFS_PACKAGES"

KICKSTART_PACKAGES="$MAKE_INITRD_PACKAGES_DEVEL $INIT_PACKAGES"
KICKSTART_PACKAGES+=" e2fsprogs btrfs-progs xfsprogs dosfstools cryptsetup lvm2"
KICKSTART_PACKAGES+=" mdadm util-linux rsync wget unzip tar cpio pwgen zstd lz4"
KICKSTART_PACKAGES+=" eject fdisk f2fs-tools"
KICKSTART_PACKAGES+=" $ZFS_PACKAGES"
