#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-or-later

MAKE_INITRD_PACKAGES="make udev libelf libkmod zlib bzlib libzstd liblzma"
MAKE_INITRD_PACKAGES+=" libbpf libjson-c5 squashfs-tools"

MAKE_INITRD_PACKAGES_DEVEL="$MAKE_INITRD_PACKAGES"
MAKE_INITRD_PACKAGES_DEVEL+=" gcc make automake autoconf bison flex"
MAKE_INITRD_PACKAGES_DEVEL+=" libkmod-devel zlib-devel bzlib-devel liblzma-devel"
MAKE_INITRD_PACKAGES_DEVEL+=" libzstd-devel libelf-devel libtirpc-devel libcrypt-devel"
MAKE_INITRD_PACKAGES_DEVEL+=" libjson-c-devel"

KERNEL_PACKAGES="kernel-latest"
INIT_PACKAGES="systemd"

SYSIMAGE_PACKAGES="$MAKE_INITRD_PACKAGES $INIT_PACKAGES"
SYSIMAGE_PACKAGES+=" pwgen mdadm lvm2 cryptsetup btrfs-progs e2fsprogs xfsprogs dosfstools reiserfsprogs"
SYSIMAGE_PACKAGES+=" grub-common grub-efi grub-pc"

KICKSTART_PACKAGES="$MAKE_INITRD_PACKAGES_DEVEL $INIT_PACKAGES"
KICKSTART_PACKAGES+=" util-linux rsync wget cryptsetup lvm2 mdadm pwgen"
KICKSTART_PACKAGES+=" e2fsprogs btrfs-progs xfsprogs dosfstools reiserfsprogs"
KICKSTART_PACKAGES+=" sfdisk unzip tar cpio eject lz4 f2fs-tools"
