#!/bin/bash

MAKE_INITRD_PACKAGES="make udev libelf1 libkmod2 zlib1g libbz2-1.0 libzstd1 liblzma5"

MAKE_INITRD_PACKAGES_DEVEL="$MAKE_INITRD_PACKAGES bison flex"
MAKE_INITRD_PACKAGES_DEVEL+=" gcc make automake autoconf pkg-config udev help2man"
MAKE_INITRD_PACKAGES_DEVEL+=" libkmod-dev libz-dev libbz2-dev liblzma-dev"
MAKE_INITRD_PACKAGES_DEVEL+=" libzstd-dev libelf-dev libtirpc-dev libcrypt-dev"

KERNEL_PACKAGES="linux$KERNEL_FLAVOR"

BOOTLOADER_EFI_PACKAGES="grub-efi"
BOOTLOADER_PC_PACKAGES="grub-pc"

SYSIMAGE_BASE_PACKAGES="$MAKE_INITRD_PACKAGES $KERNEL_PACKAGES systemd"
SYSIMAGE_EXTRA_PACKAGES="pwgen mdadm lvm2 cryptsetup btrfs-progs e2fsprogs xfsprogs dosfstools"

KICKSTART_PACKAGES="$MAKE_INITRD_PACKAGES"
KICKSTART_PACKAGES+=" e2fsprogs btrfs-progs xfsprogs dosfstools cryptsetup lvm2"
KICKSTART_PACKAGES+=" mdadm util-linux rsync wget unzip tar cpio pwgen zstd lz4"
KICKSTART_PACKAGES+=" eject fdisk"

SSH_SERVER_PACKAGES="openssh-server"

ZFS_PACKAGES="zfsutils-linux"
