#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-or-later

MAKE_INITRD_PACKAGES="make findutils udev elfutils-libelf kmod-libs zlib-ng"
MAKE_INITRD_PACKAGES+=" bzip2-libs libzstd xz-libs libxcrypt-compat json-c"
MAKE_INITRD_PACKAGES+=" squashfs-tools erofs-utils"

MAKE_INITRD_PACKAGES_DEVEL="$MAKE_INITRD_PACKAGES"
MAKE_INITRD_PACKAGES_DEVEL+=" gcc make automake autoconf bison flex gawk"
MAKE_INITRD_PACKAGES_DEVEL+=" kmod-devel zlib-ng-devel bzip2-devel xz-devel libxcrypt-devel"
MAKE_INITRD_PACKAGES_DEVEL+=" libzstd-devel elfutils-libelf-devel libtirpc-devel"
MAKE_INITRD_PACKAGES_DEVEL+=" json-c-devel"

KERNEL_PACKAGES="kernel kernel-modules"
INIT_PACKAGES="systemd"

SYSIMAGE_PACKAGES="$MAKE_INITRD_PACKAGES $INIT_PACKAGES"
SYSIMAGE_PACKAGES+=" pwgen mdadm lvm2 cryptsetup btrfs-progs e2fsprogs xfsprogs dosfstools"
SYSIMAGE_PACKAGES+=" systemd-boot-unsigned grub2-pc grub2-pc-modules"

KICKSTART_PACKAGES="$MAKE_INITRD_PACKAGES_DEVEL $INIT_PACKAGES"
KICKSTART_PACKAGES+=" e2fsprogs btrfs-progs xfsprogs dosfstools cryptsetup lvm2"
KICKSTART_PACKAGES+=" mdadm util-linux rsync wget unzip tar cpio pwgen zstd lz4"
KICKSTART_PACKAGES+=" f2fs-tools"
