#!/bin/bash

workdir="$topdir/testing/cache"
logdir="$topdir/testing/logs"
statusdir="$topdir/testing/status"

PROG="${0##*/}"
TEST=
message()
{
	printf >&2 '%s%s: %s\n' "$PROG" "${TEST:+ ($TESTNAME)}" "$*"
}

fatal()
{
	message "$*"
	exit 1
}

gh_group_start()
{
	echo "::group::$*"
}

gh_group_end()
{
	echo "::endgroup::"
}

run()
{
	message "run: $*"
	"$@"
}

cat_exec()
{
	cat > "$1"
	chmod +x "$1"
}

valid_log()
{
	if grep -qse '^IT WORKS!' "$2"; then
		message "$1 DONE"
		return 0
	else
		message "$1 FAIL"
		return 1
	fi
}

test_failed()
{
	[ ! -d "$statusdir" ] ||
		echo FAIL > "$statusdir/$VENDOR-$TESTNAME"
	printf '\n\n'
	printf 'FAIL %s\n' "$VENDOR-$TESTNAME"
	printf '\n\n'
}

test_passed()
{
	[ ! -d "$statusdir" ] ||
		echo PASS > "$statusdir/$VENDOR-$TESTNAME"
	printf '\n\n'
	printf 'PASS %s\n' "$VENDOR-$TESTNAME"
	printf '\n\n'
}

exit_handler()
{
	trap - EXIT
	if [ "$1" = 0 ]; then
		test_passed
	else
		test_failed
	fi
	exit $1
}

prepare_testsuite()
{
	mkdir -p -- \
		"$workdir" \
		"$logdir" \
		"$statusdir"
	echo FAILED \
		> "$statusdir/$VENDOR-$TESTNAME"
	if [ -e "$topdir/testing/$TESTNAME.cfg" ]; then
		sed \
			-e "s#@CMDLINE@#$BOOT_CMDLINE#g" \
			\
			"$topdir/testing/testing-$VENDOR-ks-sysimage.cfg" \
			"$topdir/testing/$TESTNAME.cfg" \
			"$topdir/testing/testing-$VENDOR-ks-initrd.cfg" \
			"$topdir/testing/testing-$VENDOR-ks-done.cfg" \
			\
			> "$workdir/ks.cfg"
	fi

	if [ -c /dev/kvm ]; then
		echo -enable-kvm -cpu host
	else
		echo -cpu max
	fi > "$workdir/qemu-cpu"

	cat > "$workdir/qemu-stdout" <<-EOF
	 -nographic
	 -serial chardev:stdio
	 -chardev stdio,mux=on,id=stdio,signal=off
	 -mon chardev=stdio,mode=readline
	EOF
}

trap 'exit_handler $?' EXIT HUP INT QUIT TERM
