#!/bin/bash -efu

topdir="$(readlink -ev "$0")"
topdir="${topdir%/*/*}"

. "$topdir/testing/sh-functions"

readonly VENDOR=fedora
readonly ARCH=x86_64
readonly IMAGE=fedora:latest
readonly KERNEL_FLAVOR=
readonly TIMEOUT=${TIMEOUT:-5m}
readonly VENDOR_CMDLINE="quiet"

readonly MAKE_INITRD_PACKAGES=(
	"make"
	"findutils"
	"udev"
	"elfutils-libelf.$ARCH"
	"kmod-libs"
	"zlib"
	"bzip2-libs"
	"libzstd"
	"xz-libs"
	"libxcrypt-compat"
)

TESTNAME="$1"; shift

case "$TESTNAME" in
	'test-root-raid1+raid5')
		# the testcase too slow for github
		exit 0
		;;
esac

KICKSTART_DISKS=0
BOOT_DISKS=0
BOOT_PROG=
BOOT_CMDLINE="root=LABEL=ROOT panic=0 $VENDOR_CMDLINE"

eval $(sed -n -e 's/^# param //p' "$topdir/testing/$TESTNAME.cfg")

readonly builddir=/srv

readonly workdir="testing/cache/$VENDOR/$TESTNAME"
readonly logdir="testing/logs/$VENDOR/$TESTNAME"

readonly top_workdir="$topdir/$workdir"
readonly top_logdir="$topdir/$logdir"

prepare_testsuite

[ "$#" -gt 0 ] ||
	set -- build-git build-sysimage build-kickstart run-kickstart run-boot

for step in "$@"; do
	case "$step" in
		build-git)
			gh_group_start "building from git tree"

			cat_exec "$top_workdir/run.sh" <<-EOF
			#!/bin/bash -efux

			dnf -y install \
			 gcc make automake autoconf \
			 ${MAKE_INITRD_PACKAGES[*]} \
			 kmod-devel zlib-devel bzip2-devel xz-devel \
			 libzstd-devel elfutils-libelf-devel.$ARCH libtirpc-devel \
			 libxcrypt-devel

			cd "$builddir"

			./autogen.sh
			./configure \
				--enable-local-build \
				--with-runtimedir=/lib/initrd1
			make
			EOF
			run podman run --rm -ti \
				--volume="$topdir:$builddir" \
				"$IMAGE" "$builddir/$workdir/run.sh"

			gh_group_end
			;;
		build-sysimage)
			if [ -z "$(podman images -an --format='1' -f reference=localhost/mi-$VENDOR:sysimage)" ]; then
				gh_group_start "creating sysimage"

				run podman image build \
					-t "localhost/mi-$VENDOR:sysimage" \
					--pull --squash --force-rm=true \
					-f - <<-EOF
				FROM $IMAGE
				RUN \
				 dnf -y install kernel$KERNEL_FLAVOR ${MAKE_INITRD_PACKAGES[*]} \
				 systemd grub2-pc mdadm lvm2 cryptsetup \
				 btrfs-progs e2fsprogs xfsprogs dosfstools \
				 pwgen
				RUN \
				 kver="\$(find /lib/modules -mindepth 1 -maxdepth 1 -printf '%f\n' -quit)"; \
				 for i in vmlinuz System.map config; do \
				  [ ! -e "/lib/modules/\$kver/\$i" ] || cp -a "/lib/modules/\$kver/\$i" "/boot/\$i-\$kver"; \
				 done
				RUN \
				 find /lib/modules \( \
				  -path '*/kernel/sound/*' -o \
				  -path '*/kernel/drivers/media-core/*' -o \
				  -path '*/kernel/drivers/power/*' -o \
				  -path '*/kernel/drivers/video/*' -o \
				  -path '*/kernel/drivers/leds/*' -o \
				  -path '*/kernel/drivers/gpio/*' -o \
				  -path '*/kernel/drivers/bluetooth/*' -o \
				  -path '*/kernel/drivers/watchdog/*' -o \
				  -path '*/kernel/drivers/nfc/*' -o \
				  -path '*/kernel/drivers/hwmon/*' -o \
				  -path '*/kernel/drivers/i2c/*' -o \
				  -path '*/kernel/drivers/iio/*' -o \
				  -path '*/kernel/drivers/isdn/*' -o \
				  -path '*/kernel/drivers/usb/*' -o \
				  -path '*/kernel/drivers/net/wireless/*' -o \
				  -path '*/kernel/drivers/net/usb/*' -o \
				  -path '*/kernel/drivers/input/touchscreen/*' -o \
				  -path '*/kernel/drivers/input/joystick/*' -o \
				  -path '*/kernel/drivers/input/misc/*' \
				  \) -delete; \
				 find /usr/share/locale/ -mindepth 3 -maxdepth 3 -type f -name '*.mo' -delete; \
				 find /usr/share/doc/ /usr/share/man/ /usr/share/info/ -mindepth 1 -delete;
				EOF

				gh_group_end
			fi

			. "$topdir/testing/sh-pack-sysimage.sh"
			;;
		build-kickstart)
			gh_group_start "creating kickstart image"

			cat_exec "$top_workdir/run.sh" <<-EOF
			#!/bin/bash -efux

			cat > /etc/initrd.mk <<EOF1
			 AUTODETECT =
			 IMAGEFILE = /boot/initrd-ks.img
			 DISABLE_FEATURES += ucode
			 FEATURES = add-modules add-udev-rules kickstart qemu rdshell modules-virtio
			 MODULES_ADD += sd_mod
			 MODULES_PRELOAD += virtio-blk virtio-scsi virtio-pci
			 KICKSTART_CONFIGS = $builddir/$workdir/ks.cfg
			 PUT_PROGS += pwgen
			EOF1

			dnf -y install kernel$KERNEL_FLAVOR ${MAKE_INITRD_PACKAGES[*]} \
			 e2fsprogs btrfs-progs xfsprogs dosfstools \
			 cryptsetup lvm2 mdadm util-linux rsync wget unzip \
			 tar cpio pwgen

			kver="\$(find /lib/modules -mindepth 1 -maxdepth 1 -printf '%f\n' -quit)"

			for i in vmlinuz System.map config; do
			    [ ! -e "/lib/modules/\$kver/\$i" ] || cp -a "/lib/modules/\$kver/\$i" "/boot/\$i-\$kver"
			done

			export PATH="$builddir/.build/dest/usr/sbin:$builddir/.build/dest/usr/bin:\$PATH"

			$builddir/.build/dest/usr/sbin/make-initrd -k \$kver

			cp -L /boot/vmlinuz-\$kver $builddir/$workdir/boot-ks-vmlinuz
			cp -L /boot/initrd-ks.img  $builddir/$workdir/boot-ks-initrd.img
			EOF

			podman run --rm -ti \
				--volume="$topdir:$builddir" \
				"$IMAGE" "$builddir/$workdir/run.sh"

			gh_group_end
			;;
		run-kickstart)
			. "$topdir/testing/sh-run-kickstart.sh"
			;;
		run-boot)
			. "$topdir/testing/sh-run-boot.sh"
			;;
		*)
			fatal "unknown step: $step"
			;;
	esac
done
