#!/bin/bash -efu

topdir="$(readlink -ev "$0")"
topdir="${topdir%/*/*}"

. "$topdir/testing/sh-functions"

readonly VENDOR=altlinux
readonly ARCH=x86_64
readonly IMAGE=alt:sisyphus
readonly KERNEL_FLAVOR=-std-def
readonly TIMEOUT=${TIMEOUT:-5m}
readonly VENDOR_CMDLINE="quiet"

readonly MAKE_INITRD_PACKAGES=(
	"make"
	"udev"
	"libelf"
	"libkmod"
	"zlib"
	"bzlib"
	"libzstd"
	"liblzma"
)

TESTNAME="$1"; shift

KICKSTART_DISKS=0
BOOT_DISKS=0
BOOT_PROG=
BOOT_CMDLINE="root=LABEL=ROOT panic=0 $VENDOR_CMDLINE"

eval $(sed -n -e 's/^# param //p' "$topdir/testing/$TESTNAME.cfg")

readonly builddir=/srv

readonly workdir="testing/cache/$VENDOR/$TESTNAME"
readonly logdir="testing/logs/$VENDOR/$TESTNAME"

readonly top_workdir="$topdir/$workdir"
readonly top_logdir="$topdir/$logdir"

prepare_testsuite

cp -TLf /usr/share/OVMF/OVMF_VARS.fd "$top_workdir"/efivars.bin

cat > "$top_workdir/qemu-cpu" <<EOF
qemu_args+=( -machine q35 )
qemu_args+=( -drive if=pflash,format=raw,readonly=on,file=/usr/share/OVMF/OVMF_CODE.fd )
qemu_args+=( -drive if=pflash,format=raw,file="$top_workdir/efivars.bin" )
EOF

[ "$#" -gt 0 ] ||
	set -- build-git build-sysimage build-kickstart run-kickstart run-boot

for step in "$@"; do
	case "$step" in
		build-git)
			gh_group_start "building from git tree"

			cat_exec "$top_workdir/run.sh" <<-EOF
			#!/bin/bash -efux

			apt-get -y -qq update
			apt-get -y -qq install \
			 gcc make automake autoconf \
			 ${MAKE_INITRD_PACKAGES[*]} \
			 libkmod-devel zlib-devel bzlib-devel liblzma-devel \
			 libzstd-devel libelf-devel libtirpc-devel libcrypt-devel

			cd "$builddir"

			./autogen.sh
			./configure \
				--enable-local-build \
				--with-runtimedir=/lib/initrd1
			make
			EOF

			run podman run --rm -ti \
				--volume="$topdir:$builddir" \
				"$IMAGE" "$builddir/$workdir/run.sh"

			gh_group_end
			;;
		build-sysimage)
			if [ -z "$(podman images -an --format='1' -f reference=localhost/mi-$VENDOR:sysimage)" ]; then
				gh_group_start "creating sysimage"

				run podman image build \
					-t "localhost/mi-$VENDOR:sysimage" \
					--pull --squash --force-rm=true \
					-f - <<-EOF
				FROM $IMAGE
				RUN \
				 printf > /etc/initrd.mk '%s\n' \
				 'AUTODETECT =' \
				 'FEATURES += compress cleanup'
				RUN \
				 rpm -ql filesystem | xargs -r mkdir -p
				RUN \
				 apt-get -y -qq update
				RUN \
				 apt-get -y -qq install kernel-image$KERNEL_FLAVOR \
				 ${MAKE_INITRD_PACKAGES[*]} \
				 sysvinit startup mingetty grub-efi mdadm lvm2 cryptsetup \
				 btrfs-progs e2fsprogs xfsprogs dosfstools reiserfsprogs \
				 pwgen
				RUN \
				 apt-get -y -qq clean
				RUN \
				 find /lib/modules \( \
				  -path '*/kernel/sound/*' -o \
				  -path '*/kernel/drivers/media-core/*' -o \
				  -path '*/kernel/drivers/power/*' -o \
				  -path '*/kernel/drivers/video/*' -o \
				  -path '*/kernel/drivers/leds/*' -o \
				  -path '*/kernel/drivers/gpio/*' -o \
				  -path '*/kernel/drivers/bluetooth/*' -o \
				  -path '*/kernel/drivers/watchdog/*' -o \
				  -path '*/kernel/drivers/nfc/*' -o \
				  -path '*/kernel/drivers/hwmon/*' -o \
				  -path '*/kernel/drivers/i2c/*' -o \
				  -path '*/kernel/drivers/iio/*' -o \
				  -path '*/kernel/drivers/isdn/*' -o \
				  -path '*/kernel/drivers/usb/*' -o \
				  -path '*/kernel/drivers/net/wireless/*' -o \
				  -path '*/kernel/drivers/net/usb/*' -o \
				  -path '*/kernel/drivers/input/touchscreen/*' -o \
				  -path '*/kernel/drivers/input/joystick/*' -o \
				  -path '*/kernel/drivers/input/misc/*' \
				  \) -delete; \
				 find /usr/share/license /usr/share/license-exception -delete; \
				 find /usr/share/locale/ -mindepth 3 -maxdepth 3 -type f -name '*.mo' -delete; \
				 find /usr/share/doc/ /usr/share/man/ /usr/share/info/ -mindepth 1 -delete; \
				 find /var/lib/apt/lists/ /var/cache/apt/ -type f -delete;
				EOF

				gh_group_end
			fi

			. "$topdir/testing/sh-pack-sysimage.sh"
			;;
		build-kickstart)
			gh_group_start "creating kickstart image"

			cat_exec "$top_workdir/run.sh" <<-EOF
			#!/bin/bash -efux

			cat > /etc/initrd.mk <<EOF1
			 AUTODETECT =
			 DISABLE_FEATURES += ucode
			 FEATURES = add-modules add-udev-rules kickstart qemu rdshell modules-virtio
			 MODULES_ADD += sd_mod
			 MODULES_PRELOAD += virtio-blk virtio-scsi virtio-pci
			 KICKSTART_CONFIGS = $builddir/$workdir/ks.cfg
			 PUT_PROGS += pwgen
			EOF1

			cat > /etc/sysconfig/installkernel <<EOF1
			 INITRD_GENERATOR=make-initrd
			 MAKE_INITRD=$builddir/.build/dest/usr/sbin/make-initrd
			 MKINITRD=$builddir/.build/dest/usr/sbin/mkinitrd-make-initrd
			EOF1

			apt-get -y -qq update

			apt-get -y -qq install \
			 e2fsprogs btrfs-progs xfsprogs dosfstools reiserfsprogs \
			 cryptsetup lvm2 mdadm sfdisk util-linux rsync wget unzip \
			 tar cpio eject sysvinit pwgen

			apt-get -y -qq install \
			 kernel-image$KERNEL_FLAVOR

			cp -L /boot/vmlinuz    $builddir/$workdir/boot-ks-vmlinuz
			cp -L /boot/initrd.img $builddir/$workdir/boot-ks-initrd.img
			EOF

			podman run --rm -ti \
				--volume="$topdir:$builddir" \
				"$IMAGE" "$builddir/$workdir/run.sh"

			gh_group_end
			;;
		run-kickstart)
			. "$topdir/testing/sh-run-kickstart.sh"
			;;
		run-boot)
			. "$topdir/testing/sh-run-boot.sh"
			;;
		*)
			fatal "unknown step: $step"
			;;
	esac
done
