#!/bin/sh -efu

. guess-functions

[ -d "$SYSFS_PATH$1"/dm ] ||
	exit 0

uuid="$(cat "$SYSFS_PATH$1"/dm/uuid)"

if [ -z "${uuid##CRYPT-*}" ]; then
	guess_feature luks
	# We need keyboard to enter password
	guess-kbd
fi
