#!/bin/bash -efu

. shell-error
. network-sh-functions

PROG="$PROG: $NET_IF"
message_time=1

for n in $net_event_list; do
	message "create event: network.$NET_EV_TYPE.$NET_EV_ACTION -> network.$n.$NET_EV_ACTION"
	net_event "network.$n.$NET_EV_ACTION" "$NET_IF"
done
