#!/bin/bash -efu

. shell-error
. shell-locks
. network-sh-functions

[ "$NET_EV_ACTION" = update ] ||
	exit 0

PROG="$PROG: $NET_IF"
message_time=1

get_iface_confdir &&
	[ -f "$confdir/hostname" ] ||
	exit 0

fd_lock 90 "$0"

name=
read -r name < "$confdir/hostname" ||:

if [ -n "$name" ]; then
	message "set hostname: $name"
	printf '%s\n' "$name" > /proc/sys/kernel/hostname
fi
