PLYMOUTH_MODULES := $(shell $(PLYMOUTH_GET_MODULES))

MODULES_ADD += $(PLYMOUTH_MODULES)
MODULES_TRY_ADD += drivers/char/agp

PUT_FEATURE_DIRS  += $(PLYMOUTH_DATADIR)
PUT_FEATURE_FILES += $(PLYMOUTH_FILES) $(PLYMOUTH_RULES)
PUT_FEATURE_PROGS += $(PLYMOUTH_PROGS)

$(call require,depmod-image)
