#!/bin/sh
#
# rc            This file is responsible for starting/stopping
#               services when the runlevel changes.
#
# Original Author:
#               Miquel van Smoorenburg, <miquels@drinkel.nl.mugnet.org>
#

. /etc/init.d/functions

# Get first argument. Set new runlevel to this argument.
export runlevel="$1"

locksys="/var/lock/subsys"
rcd="/etc/rc.d/rc$runlevel.d"

# Is there an rc directory for this new runlevel?
[ -d "$rcd" ] ||
	exit 0

# First, run the KILL scripts.
for i in "$rcd"/K*; do
	[ -x "$i" ] ||
		continue

	subsys=${i#$rcd/K??}
	s="${subsys##*.sh}"

	[ -n "$s" ] || subsys="${subsys%.sh}"

	# Check if the subsystem is already up.
	[ -f "$locksys/$subsys" ] ||
		continue

	# Bring the subsystem down.
	if [ -z "$s" ]; then
		action "Stopping $subsys:" "$i" stop
	else
		"$i" stop
	fi
done

# Now run the START scripts.
for i in "$rcd"/S*; do
	[ -x "$i" ] ||
		continue

	subsys="${i#$rcd/S??}"
	s="${subsys##*.sh}"

	[ -n "$s" ] || subsys="${subsys%.sh}"

	# Check if the subsystem is already up.
	[ ! -f "$locksys/$subsys" ] ||
		continue

	if [ -z "$s" ]; then
		action "Starting $subsys:" "$i" start
	else
		"$i" start
	fi
done
