#!/bin/sh
#
# rc            This file is responsible for starting/stopping
#               services when the runlevel changes.
#
# Original Author:
#               Miquel van Smoorenburg, <miquels@drinkel.nl.mugnet.org>
#

. /etc/init.d/functions

# Get first argument. Set new runlevel to this argument.
[ $# -eq 0 ] ||
	export runlevel="$1"

locksys="/var/lock/subsys"
rcd="/etc/rc.d/rc$runlevel.d"

# Is there an rc directory for this new runlevel?
[ -d "$rcd" ] ||
	exit 0

# Rerun ourselves through initlog
if [ -z "${IN_INITLOG-}" -a -x /sbin/initlog ]; then
	exec initlog -r "$0"
fi

# First, run the KILL scripts.
for i in "$rcd"/K*; do
	[ -x "$i" ] ||
		continue

	subsys=${i#$rcd/K??}

	# Check if the subsystem is already up.
	[ -f "$locksys/$subsys" ] ||
		continue

	"$i" stop
done

# Now run the START scripts.
for i in "$rcd"/S*; do
	[ -x "$i" ] ||
		continue

	subsys="${i#$rcd/S??}"

	# Check if the subsystem is already up.
	[ ! -f "$locksys/$subsys" ] ||
		continue

	"$i" start
done
