#!/bin/bash -efu

cwd="${0%/*}"

. "$cwd"/../../../../testing/tests/guess-feature-sh-functions

guess_feature_test_init "$0"

export FAKE_zpool="$cwd/bin/zpool"

features/zfs/guess/fstype /dev/test-root ext4 /
guess_feature_test_dump
