#!/bin/bash -efu

. guess-functions

! grep -qs -E '^[[:space:]]*(KEYTABLE|SYSFONT)=' \
		"$SYSCONFDIR/sysconfig/consolefont" \
		"$SYSCONFDIR/sysconfig/keyboard" \
		2>/dev/null ||
	guess_feature kbd
