#!/bin/sh

. /.initrd/initenv
. uevent-sh-functions
. initrd-sh-functions

DEVNAME="/dev/${DEVNAME#/dev}"

[ -z "${NO_LUKS-}" ] ||
	exit 0

[ $ID_FS_TYPE = "crypto_LUKS" ] ||
	exit 0

cryptsetup isLuks "$DEVNAME" ||
	exit 0

[ -n "$LUKS_DEV" ] ||
	LUKS_DEV="$DEVNAME"

devluks=
get_dev devluks "$LUKS_DEV" ||
	exit 0

event="$(make_event)"
showenv -q > "$event"
echo "LUKS_ROOT='$devluks'" >> "$event"
release_event luks "$event"
