#!/bin/sh -eu

hookdir=/lib/lxc-spawn

name="$1"; shift
lock="/var/lock/lxc-spawn/$name"

exit_handler() {
	local rc=$1
	trap - EXIT
	[ ! -e "$lock" ] || rm -f -- "$lock"
	exit $rc
}

trap 'exit_handler $?' EXIT
trap 'exit_handler  1' HUP PIPE INT QUIT TERM
mkdir "$lock"

while :; do
	state="$(lxc-info -sH -n "$name")" ||
		continue

	if [ "$state" == "RUNNING" ]; then
		sleep 1
		continue
	fi

	lxc-start -d -n "$name"
	lxc-wait -n "$name" -s STOPPED
done
