#!/bin/sh

. /dev/.initramfs/env
. /scripts/functions

devroot=
add() {
	# Do not mount root twice
	[ ! -e /dev/root ] || return 0

	get_dev devroot "$ROOT" || return 0

	udev-io say "Mount '$devroot' as $rootmnt"

	local roflag=-w
	[ -z "$readonly" ] || roflag=-r

	local FSTYPE="${ROOTFSTYPE:-$ID_FS_TYPE}"
	# Mount root
	if ! mount "$roflag" $ROOTFLAGS -t "$FSTYPE" "$devroot" "$rootmnt"; then
		mkdir -p /tmp/.udev-helper-error
		udev-io say "Unable to mount $devroot as $FSTYPE."
		return
	fi
	ln -sf "$devroot" /dev/root
}

add
