#!/bin/sh

msg=
run() {
	[ ! -s /conf/initramfs.conf ] || . /conf/initramfs.conf

	export PATH=/bin:/sbin:/usr/bin:/usr/sbin
	export RUN_INITRD=1
	export INIT='/sbin/init'
	export DEBUG=
	export QUIET=
	export PANIC=
	export STOP=','
	export IGNORE=','
	export rootmnt='/root'
	export udev_eventdir='/dev/.initramfs/udev-events'
	export handler_eventdir='/dev/.initramfs/handler-events'
	export readonly=1
	export RESCUE_MODULES=${RESCUE_MODULES-}
	export EXPORT_FS=${EXPORT_FS-}
	export UMOUNT_FS=${MOUNT_FS-}
}
