#!/bin/sh

msg="Loading, please wait..."
run() {
	mount -n -t sysfs    -o nodev,noexec,nosuid none /sys
	mount -n -t proc     -o nodev,noexec,nosuid none /proc

	echo > /proc/sys/kernel/hotplug
	echo /sbin/modprobe > /proc/sys/kernel/modprobe
}
