#!/bin/sh

msg="Loading, please wait..."
run() {
	mount -n -t sysfs -o nodev,noexec,nosuid none /sys
	mount -n -t proc  -o nodev,noexec,nosuid none /proc
	mount -n -t tmpfs -o size=10M,mode=0755  udev /dev

	mkdir /dev/.initramfs /dev/pts /dev/shm

	mount -n -t devpts devpts /dev/pts

	mknod /dev/ram     b 1 1
	mknod /dev/null    c 1 3
	mknod /dev/zero    c 1 5
	mknod /dev/full    c 1 7
	mknod /dev/random  c 1 8
	mknod /dev/kmsg    c 1 11
	mknod /dev/systty  c 4 0
	mknod /dev/tty0    c 4 0
	mknod /dev/tty1    c 4 1
	mknod /dev/tty     c 5 0
	mknod /dev/console c 5 1
	mknod /dev/ptmx    c 5 2

	echo > /proc/sys/kernel/hotplug
	echo /sbin/modprobe > /proc/sys/kernel/modprobe
}
