#!/bin/sh

msg="Parsing command line options..."
run() {
	local x s n l=
	local CMDLINE_PARAMS

	read CMDLINE </proc/cmdline
	export CMDLINE

	for x in /etc/initrd/*; do
		if [ -s "$x" ]; then
			. "$x"
			l="$l ${CMDLINE_PARAMS-}"
		fi
	done

	for x in $CMDLINE; do
		s="$(replace -s= "[a-z]-." "[A-Z]__" "$x")"
		for n in $l; do
			case "$s" in
				RW)	readonly=	;;
				RO)	readonly=1	;;
				$n)	export "$s=1"	;;
				$n=*)	export "$s"	;;
			esac
		done
	done

	STOP=",$STOP,"
	IGNORE=",$IGNORE,"
}
