#!/bin/sh

msg='Defining root device...'
run() {
	case "$ROOT" in
		LABEL=*)
			echo "ENV{ID_FS_USAGE}==\"filesystem|other\", ENV{ID_FS_LABEL}==\"${ROOT#LABEL=}\", SYMLINK+=\"root\"" > /etc/udev/rules.d/99-root.rules
			ROOT="/dev/root"
			;;
		UUID=*)
			echo "ENV{ID_FS_USAGE}==\"filesystem|other\", ENV{ID_FS_UUID}==\"${ROOT#UUID=}\", SYMLINK+=\"root\"" > /etc/udev/rules.d/99-root.rules
			ROOT="/dev/root"
			;;
		/dev/nfs)
			BOOT=nfs
			;;
	esac
}
