#!/bin/sh

msg='Starting udevd...'
run() {
	printenv -q > /dev/.initramfs/env

	mkdir -p /dev/.udev/db/
	udevd --daemon

	mkdir -p /dev/.udev/queue/
	udevadm trigger --attr-match dev
	udevadm settle
}
