#!/bin/sh

msg='Starting udevd...'
run() {
	printenv -q > /dev/.initramfs/env

	mkdir -p /dev/.udev/db/
	udevd --daemon

	mkdir -p /dev/.udev/queue/
	udevadm trigger --attr-match dev
	udevadm settle

	if [ -d /tmp/.initramfs-shell ]; then
		nuke /tmp/.initramfs-shell
		return 1
	fi
}
