#!/bin/sh

msg='Starting udevd...'
run() {
	printenv -q > /dev/.initramfs/env

	mkdir -p /dev/.udev/db/
	udevd --daemon

	mkdir -p /dev/.udev/queue/
	udevadm trigger
	udevadm settle

	if [ -d /tmp/.udev-helper-error ]; then
		nuke /tmp/.udev-helper-error
		return 1
	fi
}
