#!/bin/sh

msg='Loading modules after udevd...'
run() {
	load_modules postudev

	udevadm trigger
	udevadm settle

	if [ -d /tmp/.udev-helper-error ]; then
		nuke /tmp/.udev-helper-error
		return 1
	fi
}
