#!/bin/sh

msg='Trying to resume system...'

try_to_resume() {
	[ -n "$resume" ] || return 0

	if [ ! -e /sys/power/resume ]; then
		verbose "Warning: Kernel does not support resume - doing normal boot"
		return
	fi

	if ! wait_device "$resume" "Waiting for resume device"; then
		verbose "Warning: Resume device $resume not found - doing normal boot"
		return
	fi

	# hardcode path, uswsusp ships an resume binary too
	/bin/resume "$resume"
}

try_to_resume2() {
	[ -n "$resume2" ] || return 0

	if [ ! -e /sys/power/suspend2/do_resume ]; then
		verbose "Warning: Kernel does not support resume"
		return 0
	fi
	echo > /sys/power/suspend2/do_resume
}

run() {
	# Try to resume before touching the root device
	try_to_resume
	try_to_resume2
}
