#!/bin/sh

msg='Waiting root file system...'
run() {
	# Default delay is 180s
	local sec=$((${ROOTDELAY:-180}*10))
	while [ "$sec" -gt 0 ] && [ ! -e "$rootmnt/$INIT" ]; do
		wait_unlock tty
		sleep 0.1
		sec=$(($sec-1))
	done
	[ -e "$rootmnt/$INIT" ] || return 1
}
