#!/bin/sh

msg='Reading udev config from the real filesystem if possible...'
run() {
	if [ -e $rootmnt/etc/udev/udev.conf ]; then
		. $rootmnt/etc/udev/udev.conf
	elif [ -e /etc/udev/udev.conf ]; then
		. /etc/udev/udev.conf
	fi
	[ "$use_initramfs_dev" != 1 ] ||
		INITRAMFS_DEV="${INITRAMFS_DEV:-1}"
}
