#!/bin/sh

msg='Preparing to boot real system...'
run() {
	while [ ! -x "$rootmnt/$INIT" ]; do
		shell "Target filesystem doesn't have $INIT"
	done

	umount /sys
	umount /proc
	umount /dev/pts

	# If /dev was not moved to the real filesystem, unmount it
	[ "$use_initramfs_dev" = 1 ] || umount -l /dev
}
