#!/bin/sh

msg='Asking all remaining processes to terminate...'
killall() {
	local i r=0 omit=' 1 '
	while read i; do
		omit="$omit$i "
	done < "$omitproc"
	for i in /proc/*; do
		i="${i#/proc/}"
		[ -n "${omit##* $i *}" -a -n "${i##*[!0-9]*}" -a -f "/proc/$i/exe" ] ||
			continue
		kill $1 $i
		sleep 0.1
		kill -0 $i 2>/dev/null && r=1
	done
	return $r
}

run() {
	local i=5
	if killall -15; then
		for i in 1 2 3 4 5; do
			killall -18 || break
		done
		sleep 0.1
	fi
	if [ "$i" = 5 ]; then
		verbose 'Killing all remaining processes...'
		killall -9
	fi
}
