#!/bin/sh

msg='Umounting filesystems...'
run() {
	umount /sys
	umount /proc
	umount /dev/pts

	# If /dev was not moved to the real filesystem, unmount it
	[ -n "$INITRAMFS_DEV" ] || umount -l /dev
}
