#!/bin/sh

msg='Running init...'
run() {
	umount /sys
	umount /proc
	umount /dev/pts

	# If /dev was not moved to the real filesystem, unmount it
	[ -n "$INITRAMFS_DEV" ] || umount -l /dev

	set_lock initrd

	# Chain to real filesystem
	exec run-init "$rootmnt" "$INIT" "$@" <"$rootmnt"/dev/console >"$rootmnt"/dev/console
}
