KEYBOARD_MODLUES_DETECTED = $(shell [ ! -s $(GUESSDIR)/kbdmodules ] || cat $(GUESSDIR)/kbdmodules)

ifeq "$(KEYBOARD_MODLUES_DETECTED)" ''
KEYBOARD_MODLUES_DETECTED = $(KEYBOARD_DEFAULT_MODULES)
endif

RESCUE_MODULES += $(KEYBOARD_MODLUES_DETECTED)
