#!/bin/bash -eu

. features/network/data/bin/network-cmdline-sh-functions

testcase()
{
	printf 'IFNAME: %s\n' "$1"

	local interface='' macaddr=''

	ifname_to_var "$1"

	printf ' - interface: %s\n' "$interface"
	printf ' - macaddr  : %s\n' "$macaddr"
	printf '\n'
}

failed()
{
	printf ' - FAILED\n'
	printf '\n'
}

# expect success
(testcase "bootif0:8b:3f:d2:1c:d6:bc") || failed
(testcase "bootif0:00:00:10:29:fe:80:00:00:00:00:00:00:b8:ce:f6:03:00:99:4c:42") || failed

# expect fail
(testcase "bootif0:8b:3f:d2:1c:d6:b") || failed
(testcase "bootif0:8b:xz:d2:1c:d6:bc") || failed
(testcase "bootif0:8b:3f:d2:1c:d6") || failed
(testcase "bootif0:8b:3f:d2:1c:d6:bc:ab") || failed
(testcase "bootif0:00:00:10:29:fe:80:00:00:00:00:00:00:b8:ce:f6:03:00:99:4c:42:a0") || failed
