#!/bin/sh

. /.initrd/initenv
. uevent-sh-functions

message_time=1

handler() {
	[ -d "$MOUNTPOINT" ] ||
		return 1
	mountpoint -q "$MOUNTPOINT" ||
		mount ${DEBUG:+-v} "$roflag" "$MOUNTPOINT" ||
		return 1
}

roflag=-w
[ -z "$READONLY" ] || roflag=-r

for e in "$eventdir"/mountdev.*; do
	[ -e "$e" ] || break
	( . "$e"; handler; ) && done_event "$e" ||:
done
