#!/bin/bash

. /.initrd/initenv
. uevent-sh-functions

message_time=1

handler() {
	[ -d "$MOUNTPOINT" ] ||
		return 1
	! mountpoint -q "$MOUNTPOINT" ||
		return 0
	rc=0
	msg="$(mount -v "$roflag" "$MOUNTPOINT" 2>&1)" ||
		rc=1
	message "$msg"
	return $rc
}

roflag=-w
[ -z "$READONLY" ] || roflag=-r

for e in "$eventdir"/mountdev.*; do
	[ -e "$e" ] || break
	( . "$e"; handler; ) && done_event "$e" ||:
done
