#!/bin/sh

. /dev/.initramfs/env
. /scripts/functions

# md=<md device no.>,<raid level>,<chunk size factor>,<fault level>,dev0,dev1,...,devn
# md=<md device no.>,dev0,dev1,...,devn
# md=d<md device no.>,dev0,dev1,...,devn

split() {
	local IFS=, str="$1"
	set -- $str
	printf '%s' "$*"
}

[ -n "$MD" ] ||
	exit 0

devlist= lvl dev found=

if [ -z "${MD#d*}" ]; then
	devlist="${MD#*,}"
else
	MD="${MD#*,}"
	lvl="${MD%%,*}"
	[ "$lvl" -le 0 -o "$lvl" -gt 0 ] 2>/dev/null &&
		devlist=${MD#*,*,*,} ||
		devlist="$MD"
fi

for dev in $(split "$devlist"); do
	if [ "$dev" = "$DEVNAME" -o "$dev" = "/dev/$DEVNAME" ]; then
		found=1
		break
	fi
done

[ -n "$found" ] ||
	exit 0

echo > "$eventdir"/raid/event
