ifeq "$(RDSHELL)" ''
RDSHELL = shell
endif
ifneq "$(RDSHELL_PASSWORD)$(RDSHELL_COPY_PASSWORD_FROM_USER)" ''
RDSHELL = login
endif

RHSHELL_DIRS := $(shell env \
	"RDSHELL=$(RDSHELL)" \
	"RDSHELL_PASSWORD=$(RDSHELL_PASSWORD)" \
	"RDSHELL_COPY_PASSWORD_FROM_USER=$(RDSHELL_COPY_PASSWORD_FROM_USER)" \
	$(FEATURESDIR)/rdshell/bin/add-login dirs)

PUT_FEATURE_DIRS += $(RHSHELL_DIRS)
