#!/bin/bash -efu
# SPDX-License-Identifier: GPL-3.0-or-later

. guess-functions

if [ -f "$SYSFS_PATH$1"/modalias ]; then
	modalias=
	readline modalias "$SYSFS_PATH$1"/modalias

	[ -n "${modalias##scsi:*}" ] ||
		guess_module sd_mod
fi
