#!/bin/bash -efu
# SPDX-License-Identifier: GPL-3.0-or-later

[ -f "$SYSFS_PATH$1"/modalias ] ||
	exit 0

. guess-functions

modalias=
readline modalias "$SYSFS_PATH$1"/modalias

[ -n "${modalias##scsi:*}" ] ||
	guess_module sd_mod
