#!/bin/sh
# NFS filesystem mounting

# FIXME This needs error checking

DEVICE=${DEVICE:-eth0}

# parse nfs bootargs + launch ipconfig and nfsmount
do_nfsmount()
{
	NFSOPTS="-o retrans=10"

	case "$NFSROOT" in
		''|auto)
			# get nfs root from dhcp
			NFSROOT="$ROOTPATH"
			;;
		*)
			# nfsroot=[<server-ip>:]<root-dir>[,<nfs-options>]
			[ -n "${NFSROOT##*,*}" ] ||
				NFSOPTS="-o ${NFSROOT#*,}"

			NFSROOT=${NFSROOT%%,*}
			;;
	esac

	[ -z "${NFSROOT##*:*}" ] ||
		NFSROOT="$ROOTSERVER:$ROOTPATH"

	roflag='-o rw'
	[ -z "$readonly" ] || roflag='-o ro'

	nfsmount -o nolock $roflag $NFSOPTS "$NFSROOT" "$rootmnt"
}

# NFS root mounting
mountroot()
{
	modprobe -q nfs
	# For DHCP
	modprobe -q af_packet

	configure_network

	! do_nfsmount || return 0

	# Default delay is around 180s
	sec=$(( ${ROOTDELAY:-180} * 10 ))

	# loop until nfsmount succeds
	while [ "$delay" -gt 0 ] && [ ! -e "$rootmnt/$INIT" ]; do
		/bin/sleep 1
		verbose "Retrying nfs mount"
		do_nfsmount
		sec=$(( $sec - 1 ))
	done
}
