#!/bin/sh
### BEGIN INIT INFO
# Provides:            lxc-init
# Required-Start:      mountvirtfs
# Should-Start:        $syslog
# Required-Stop:
# Should-Stop:
# Default-Start:       3 4 5
# Default-Stop:
# Short-Description:   TODO
# Description:         TODO
### END INIT INFO

[ "$1" = start ] || exit 0

. /.initrd/initenv

dest=/run/initramfs

mkdir -p -- "$dest"
cd "$dest"

cp /.initrd/kernenv .

read initargs </.initrd/initargs

cat >init<<EOF
#!/bin/sh
unset container
. /run/initramfs/kernenv
exec "$INIT" $initargs
EOF

chmod +x init
