SSHFS_DIRS := $(shell $(shell_export_vars) $(FEATURESDIR)/sshfsroot/bin/get-dirs)

MODULES_PRELOAD	+= $(SSHFS_PRELOAD)

PUT_FEATURE_DIRS  += $(SSHFS_DATADIR) $(SSHFS_DIRS)
PUT_FEATURE_PROGS += $(SSHFS_PROGS)
