#!/bin/bash
# Copyright (C) 2002 Ivan Zakharyaschev <imz@altlinux.ru>.
# Copyright (C) 2002,2003 Dmitry V. Levin <ldv@altlinux.org>.

# Offset from right margin of the screen to start status labels at.
[ -n "${RES_OFFSET-}" ] && [ "$RES_OFFSET" -gt 0 ] 2>/dev/null || RES_OFFSET=8

# Terminal sequence to move to that position.
TO_COL=$(( ${COLUMNS:-80} - $RES_OFFSET ))
[ "$TO_COL" -gt 0 ] 2>/dev/null || TO_COL=1

printf -v TO_COL "\033[%dG" "$TO_COL"

# Enumerate colors
# "${BLACK:=0}" "${RED:=1}" "${GREEN:=2}" "${YELLOW:=3}" "${BLUE:=4}" "${MAGENTA:=5}" "${CYAN:=6}" "${WHITE:=7}"

printf -v COLOR_SUCCESS "\033[1m\033[3%dm"   "${GREEN:-2}"
printf -v COLOR_FAILURE "\033[1m\033[3%dm"   "${RED:-1}"
printf -v COLOR_WARNING "\033[1m\033[3%dm"   "${YELLOW:-3}"
printf -v COLOR_INFO    "\033[1m\033[3%dm"   "${CYAN:-6}"
printf -v COLOR_BANNER  "\033[3%dm\033[4%dm" "${BLUE:-4}" "${YELLOW:-3}"
printf -v COLOR_NORMAL  "\033[39;49m\033[0;10m"
