#!/bin/sh

. /dev/.initramfs/env
. /scripts/functions

DEVNAME="/dev/${DEVNAME#/dev}"
cryptsetup isLuks "$DEVNAME" ||
	exit 0

[ -n "$LUKS_DEV" ] ||
	LUKS_DEV="$DEVNAME"

devluks=
get_dev devluks "$LUKS_DEV" ||
	exit 0

event="$(mk_event luks)"
showenv -q > "$event"
echo "LUKS_ROOT='$devluks'" >> "$event"
