#!/bin/bash -eu
# SPDX-License-Identifier: GPL-3.0-or-later

. sh-functions
. guess-functions

$TRACE_SOURCE "Processing ..."

cmdline=
readline cmdline "$PROCFS_PATH/cmdline"

resume=
for x in $cmdline; do
	[ -z "${x##resume=*}" ] ||
		continue
	resume=${x#resume=}
done

[ -n "$resume" ] ||
	exit 0

device_list="$(get_device "$resume")" ||
	fatal "Unable to find resume device"

for device_file in $device_list; do
	majmin="$(get_majmin "$device_file")" ||
		continue

	# kernel >= 2.6.27
	guess_device "/dev/block/$majmin"
done
