#!/bin/bash -eu

. guess-functions

devname="$1"; shift
fstype="$1"; shift

[ "$fstype" = 'btrfs' ] ||
	exit 0

uuid="$(blkid -o value -s UUID -c /dev/null "$devname")"

for path in "$SYSFS_PATH/fs/btrfs/$uuid/devices"/*; do
	[ -e "$path" ] ||
		break
	guess_device "${path#$SYSFS_PATH}"
done

guess_feature 'btrfs'
