#!/bin/bash -e
# SPDX-License-Identifier: GPL-3.0-or-later

. guess-functions

$TRACE_SOURCE "Processing ..."

depinfo ${KERNEL:+-k "$KERNEL"} --no-deps --no-firmware lkrg p_lkrg 2>/dev/null |grep -e '^module ' ||
	exit 0

guess_feature "lkrg"
