#!/bin/bash -efu

cwd="${0%/*}"

. "$cwd"/../../../../testing/tests/guess-feature-sh-functions

guess_feature_test_init "$0"

mkdir -p -- "$SYSFS_PATH/devices/test-parent"
printf '%s\n' 'pci' > "$SYSFS_PATH/devices/test-parent/subsystype"

features/nvmf/guess/device /devices/test-parent
guess_feature_test_dump
