#!/bin/bash -efu

export PATH=/sbin:/usr/sbin:/usr/local/sbin:/bin:/usr/bin:/usr/local/bin

[ -d /.initrd ] ||
	mkdir -p /.initrd

# Save kernel environment and init arguments
[ -f /.initrd/kernenv ] ||
	/bin/environ -q -u _,PWD,SHLVL > /.initrd/kernenv

# Create storage for init environment
:> /.initrd/initenv

# Backward compatibility
x=/sbin/init-bin
[ ! -x "$x" ] || exec "$x"

trap : INT TSTP QUIT HUP

x=/etc/rc.d/rc.sysinit
[ ! -x "$x" ] || setsid "$x" ||:

. initrd-sh-functions

create_foreground_session services /etc/rc.d/rc.runlevel ||:

exec /etc/rc.d/rc.sysexec "$@"
