#!/bin/bash -efu

cwd="${0%/*}"

. "$cwd"/../../../../testing/tests/guess-feature-sh-functions

guess_feature_test_init "$0"

mkdir -p -- "$SYSFS_PATH/devices/test-dm"

features/devmapper/guess/device /devices/test-dm
guess_feature_test_dump
