#!/bin/bash -efu

. initrd-sh-functions
. rdshell-sh-functions

. shell-error

PID="$$"

exit_handler()
{
	trap - EXIT
	[ "$1" = 0 ] ||
		kill -15 -$PID >/dev/null 2>&1
	exit "$1"
}

trap 'exit_handler $?' EXIT

mkdir -p /var/run
echo $PID > /var/run/rootdelay.pid

while :; do
	# Waiting for cmdline service
	. /.initrd/initenv
	[ -z "${ROOTDELAY-}" ] ||
		break
	sleep 0.2
done

if [ -n "${RDSHELL-}" ]; then
	console_open "Emergency shell" withlock
	exit
fi

ROOTDELAY=${ROOTDELAY:-180}
delay=$ROOTDELAY
while [ "$delay" -gt 0 ] && [ ! -x "$rootmnt/$INIT" ]; do
	if ! rootdelay_paused; then
		if [ -z "${QUIET-}" ] && [ $delay -lt $ROOTDELAY ] && [ $(( $delay % 15 )) -eq 0 ]; then
			while ! console_lock; do
				sleep 0.2
			done

			PROG=initramfs \
			message "Waiting for root ..." >/dev/console 2>&1 ||:

			console_unlock
		fi

		delay=$(($delay - 1))

		if [ "$delay" -eq 0 ] && ! resume_checked; then
			set_resume_checked
			delay=$ROOTDELAY
		fi
	fi
	sleep 1
done

[ ! -x "$rootmnt/$INIT" ] ||
	exit 0

# Disallow console access
[ "${PANIC-}" != "0" ] || reboot -f

console_open "The waiting time expired!" withlock
