#!/bin/bash -efu
# SPDX-License-Identifier: GPL-3.0-or-later

driver=
if [ -f "$SYSFS_PATH/$1"/uevent ]; then
	driver="$(sed -n -e 's/^DRIVER=\(uas\|usb-storage\)$/\1/p' "$SYSFS_PATH/$1"/uevent)"
fi

if [ -z "$driver" ] && [ -e "$SYSFS_PATH/$1"/driver ]; then
	t="$(readlink -ev "$SYSFS_PATH/$1"/driver 2>/dev/null)" ||:
	case "${t##*/}" in
		uas|usb-storage) driver="${t##*/}"
			;;
	esac
fi

[ -n "$driver" ] ||
	exit 0

. guess-functions

guess_module "$driver"
