#!/bin/bash -efu
# SPDX-License-Identifier: GPL-3.0-or-later

found=
if [ -f "$SYSFS_PATH/$1"/uevent ]; then
	! grep -qs '^DRIVER=usb-storage$' "$SYSFS_PATH/$1"/uevent ||
		found=1
fi

if [ -z "$found" ] && [ -e "$SYSFS_PATH/$1"/driver ]; then
	t="$(readlink -ev "$SYSFS_PATH/$1"/driver 2>/dev/null)" ||:
	case "${t##*/}" in
		usb-storage) found=1
			;;
	esac
fi

[ -n "$found" ] ||
	exit 0

. guess-functions

guess_module usb-storage
