#!/bin/sh -efu

. guess-functions

found=
if [ -f "$SYSFS_PATH/$1"/uevent ]; then
	! egrep '^DRIVER=(ub|usb-storage)$' "$SYSFS_PATH/$1"/uevent ||
		found=1
fi

if [ -z "$found" -a -e "$SYSFS_PATH/$1"/driver ]; then
	t="$(readlink -ev "$SYSFS_PATH/$1"/driver 2>/dev/null)" ||:
	case "${t##*/}" in
		ub|usb-storage) found=1
			;;
	esac
fi

[ -n "$found" ] ||
	exit 0

guess_module ub
guess_module usb-storage
