#!/bin/bash -efu
# SPDX-License-Identifier: GPL-3.0-or-later

. guess-functions

[ -d "$SYSFS_PATH$1"/dm ] ||
	exit 0

uuid=
readline uuid "$SYSFS_PATH$1"/dm/uuid

[ -n "${uuid##mpath-*}" ] ||
	guess_feature multipath
