#!/bin/sh -eu

. sh-functions

cd "$rootdir"

mkfifo .initrd/rdshell

for init in /sbin/init.initrd /sbin/init; do
	[ -x "$init" ] ||
		continue

	put-file "$rootdir" "$init"

	mv $verbose ".$init" ./sbin/init-bin
	ln -s init-bin ./sbin/telinit

	break
done

for i in rc0 rc1 rc2 rc3 rc4 rc5 rc6 init; do
	mkdir -p etc/rc.d/$i.d
	ln -s rc.d/$i.d etc/$i.d
done
