#!/bin/sh -efu

. /scripts/functions

handler() {
	. "/tmp/net-$INTERFACE.conf"

	# get nfs root from dhcp
	if [ "$NFSROOT" = 'auto' ]; then
		NFSROOT="$ROOTPATH"
		[ "${NFSROOT#*:}" != "$NFSROOT" ] || NFSROOT="$ROOTSERVER:$ROOTPATH"
	else
	# nfsroot=[<server-ip>:]<root-dir>[,<nfs-options>]
		[ "${NFSROOT#*,}" = "$NFSROOT" ] || NFSOPTS="-o ${NFSROOT#*,}"
		NFSROOT=${NFSROOT%%,*}
		[ "${NFSROOT#*:}" != "$NFSROOT" ] || NFSROOT="$ROOTSERVER:$NFSROOT"
	fi

	# nfs options are an optional arg
	[ -n "$NFSOPTS" ] || NFSOPTS="-o retrans=10"

	local roflag='-o rw'
	[ -z "$readonly" ] || roflag='-o ro'

	nfsmount -o nolock $roflag $NFSOPTS "$NFSROOT" "$rootmnt" ||
		return 0
	message "Mount '$NFSROOT' as $rootmnt"
	ln -s /dev/nfs /dev/.initramfs/root
}

rc=0
for e in "$eventdir"/nfsroot/*; do
	[ -f "$e" ] && [ ! -e /dev/.initramfs/root ] ||
		break

	( . "$e"; handler; ) ||
		rc=1
done

exit $rc
