#!/bin/bash -efu

. pipeline-sh-functions

check_parameter GETIMAGE
url="$(get_parameter GETIMAGE)"

if [ -n "${url##file://*}" ]; then
	n=0
	while [ "$n" != 5 ]; do
		! wget -O "$datadir/image" "$url" ||
			break
		n=$(($n + 1))
		sleep 3
	done
else
	target="${url#file://}"

	pipe_gpg_verify "getimage" "$target.asc" "$target"

	cp -f -- "$target" "$datadir/image"
fi
modprobe -q 'devname:loop-control' ||:
run mount -o ro,loop "$datadir/image" "$destdir"
