#!/bin/bash -efu

check_parameter MOUNTFS
target="$(get_parameter MOUNTFS)"
target="$(resolve_target "$target")"

opts=
[ ! -c "$target" ] && [ ! -b "$target" ] ||
	opts='ro,loop'

run mount ${opts:+-o $opts} "$target" "$destdir"
