#!/bin/bash -efu

. pipeline-sh-functions

check_parameter MOUNTFS
param="$(get_parameter MOUNTFS)"
target="$(resolve_target "$param")"

[ -n "$target" ] ||
	fatal "unable to resolve: $param"

opts="$(get_parameter MOUNTFS_OPTS)"

if [ ! -c "$target" ] && [ ! -b "$target" ]; then
	modprobe -q 'devname:loop-control' ||:
	opts="${opts:+$opts,}ro,loop"
fi

run mount ${opts:+-o $opts} "$target" "$destdir"
