#!/bin/bash -efu

check_parameter WAITDEV
devspec="$(get_parameter WAITDEV)"
envfile=/.initrd/pipeline/waitdev

while [ -n "$devspec" ]; do
	if [ -f "$envfile" ]; then
		. "$envfile"

		devfile="$(get_parameter WAITDEV_FILE)"

		if [ -n "$devfile" ]; then
			if [ ! -e "$destdir/dev" ]; then
				target="$(readlink -f "$devfile")"
				run cp -a -- "$target" "$destdir/dev"
			fi
			break
		fi
	fi
	sleep 1
done
