#!/bin/sh

. /scripts/functions

handler() {
	mountpoint -q "$rootmnt" ||
		mount ${DEBUG:+-v} "$roflag" "$rootmnt" ||
		return 1
}

roflag=-w
[ -z "$readonly" ] || roflag=-r

rc=0
for e in "$handler_eventdir"/rootdev.*; do
	( . "$e"; handler; ) ||
		rc=1
	done_event "$e"
done

exit $rc
