#!/bin/sh -efu

. /dev/.initramfs/env
. /scripts/functions

[ -n "$IP" ] ||
	exit 0

if [ "$INTERFACE" = 'lo' ]; then
	iface=
	i=0
	while [ "$iface" != 'lo' -a $i -lt $IP ]; do
		eval "IPOPTS=\"\$IP$i\""
		iface="${IPOPTS%:*}"
		iface="${iface##*:}"
		i=$(($i+1))
	done

	if [ "$iface" != 'lo' ]; then
		export IP0=127.0.0.1:::::lo:none
		export IP=1
	fi
fi


event="$(mk_event netdev)"
showenv -q > "$event"
