#!/bin/sh -efu

. /dev/.initramfs/env
. /scripts/functions

if [ "$INTERFACE" = 'lo' ]; then
	export IP0='127.0.0.1:::::lo:none'
	export IP=1
fi

[ -n "$IP" ] ||
	exit 0

event="$(mk_event netdev)"
showenv -q > "$event"
