#!/bin/sh -efu

. /dev/.initramfs/env
. /scripts/functions

devroot=
get_dev devroot "$ROOT" ||
	exit 0

if [ -n "$devroot" ]; then
	event="$(mk_event rootdev)"
	showenv -q > "$event"
	echo "INIT_ROOT='$devroot'" >> "$event"
fi
