#!/bin/bash -efu

. shell-error
. /.initrd/initenv

[ -n "${BOOT_CONFIG-}" ] ||
	fatal "config file not found"

. rdshell-sh-functions

console_lock
exec < /dev/console >/dev/console 2>&1

export NEWT_COLORS_FILE="/home/root/.newtrc"

mkdir -p /tmp/bootmenu
cd /tmp/bootmenu

setsid -c /bin/bootmenu "$BOOT_CONFIG" .

read kernel < kernel
read initrd < initrd
read append < append

ln -sf -- "$rootmnt$BOOT_PREFIX" /boot

kexec \
	--load "$kernel" \
	${initrd:+--initrd="$initrd"} \
	${append:+--append="$append"}
kexec -x -e

setsid /bin/sh -l

console_unlock
