#!/bin/bash -efu

. /.initrd/initenv

. shell-error
. shell-locks

[ -n "${BOOT_CONFIG-}" ] ||
	fatal "config file not found"

exec < /dev/console >/dev/console 2>&1
fd_lock 90 /dev/console

export NEWT_COLORS_FILE="/home/root/.newtrc"

mkdir -p /tmp/bootmenu
cd /tmp/bootmenu

setsid -c /bin/bootmenu "$BOOT_CONFIG" . 90<&-

# shellcheck disable=SC2094,SC2162
read kernel < kernel

# shellcheck disable=SC2094,SC2162
read initrd < initrd

# shellcheck disable=SC2094,SC2162
read append < append

ln -sf -- "${BOOT_CONFIG%/*}" /boot

kexec \
	--load "/boot/$kernel" \
	${initrd:+--initrd="/boot/$initrd"} \
	${append:+--append="$append"} 90<&-
kexec -x -e 90<&-

setsid /bin/sh -l 90<&-

fd_unlock 90
