#!/bin/sh -efu

. /.initrd/initenv

exec 2>/dev/null

# It is not currently limit since the execution of programs
# takes time, which is not counted. But we do not want to use
# additional utilities to calculate the time limit.
sec=$(( ${ROOTDELAY:-180} * 10 ))

while [ "$sec" -gt 0 ]; do
	sleep 0.1 ||
		exit 0
	sec=$(( $sec - 1 ))
done

[ ! -x "$rootmnt/$INIT" ] ||
	exit 0

echo "The waiting time expired!" > /.initrd/shell
