#!/bin/bash -efu

cwd="${0%/*}"

. "$cwd"/../../../../testing/tests/guess-feature-sh-functions

guess_feature_test_init "$0"

cat > "$PROCFS_PATH/filesystems" <<-'EOF'
nodev	sysfs
nodev	tmpfs
EOF

features/rootfs/guess/fstype /dev/test-root ext4
guess_feature_test_dump
