#!/bin/bash -efu

. guess-functions

devname="$1"; shift
fstype="$1"; shift

fsmod="${fstype%%.*}"

found=
while read -r fsname more; do
	if [ "${more:-$fsname}" = "$fsmod" ]; then
		found=1
		break
	fi
done < /proc/filesystems

[ -n "$found" ] ||
	fatal "No filesystem found for '$fstype'"

depinfo ${KERNEL:+-k "$KERNEL"} -D "fs-$fsmod" >/dev/null 2>&1 ||
	exit 0

guess_modalias "fs-$fsmod"
