#!/bin/sh -efu

. ${TOOLSDIR:?}/sh-functions

fstab="${FSTAB:?}"

while read dev mpoint fstype opts freq passno; do
	[ -n "${dev##\#*}" -a "$mpoint" = / ] ||
		continue
	add-module "$fstype"
done < "$fstab"
