#!/bin/sh -efu

. sh-functions

[ "$#" -gt 0 ] || return 0

l=
for m; do
	m="${m##*/}"
	m="${m%.ko*}"
	l="${l:+$l }$m"
done

add-module "$@"
printf 'RESCUE_MODULES="%s"\n' "$l" >> "$rootdir"/etc/initrd/initramfs.conf
