#!/bin/sh -eu

. sh-functions
. shell-signal

kmodules_list=
exit_handler() {
	[ ! -f "$kmodules_list" ] ||
		rm -f -- "$kmodules_list"
}

set_cleanup_handler exit_handler
kmodules_list="$(mktemp "$workdir/$PROG.XXXXXXXXX")"

find "$rootdir/$kernel_modules_dir" \
		-type f -name '*.ko*' \
		-printf '%f %p\n' |
	sed -e 's/^\([^[:space:]]\+\)\.ko\(\.[^\.]\+\)\? /\1 /' |
	sort -uo "$kmodules_list"

for f in "$kmoddepsdir"/*; do
	[ -x "$f" ] ||
		continue
	verbose "Running '${f##*/}' ..."
	"$f" "$kmodules_list"
done
