#!/bin/sh -efu

. shell-error

param="$1"; shift

module="${param%%:*}"
arg="${param#*:}"

[ -f "$autodetectdir/detect-$module" ] ||
	fatal "Unknown module: $module"

"$autodetectdir/detect-$module" "$arg" |
while read f; do
	message "$f"
	put-file "$f"
done
