#!/bin/sh -efu

. sh-functions
. shell-error

for param; do
	module="${param%%:*}"
	arg=
	[ -n "${param##*:*}" ] || arg="${param#*:}"

	[ -f "$autodetectdir/detect-$module" ] ||
		fatal "Unknown module: $module"

	"$autodetectdir/detect-$module" "$arg" |
	while read f; do
		name="${f##*/}"
		name="${name%.ko}"

		check_blacklist "$name" ||
			continue

		[ -n "$verbose" ] || message "$f"
		put-file "$f"
	done
done

