#!/bin/sh -efu

. ${TOOLSDIR:?}/sh-functions

target="$1"; shift
action="$1"; shift

mkdir -p -- "$statedir/$target"

case "$action" in
	check)
		[ -f "$statedir/$target/$action" ] &&
			exit 0 || exit 1
		;;
	state)
		:> "$statedir/$target/$action"
		;;
esac
