#!/bin/sh -efu

. ${TOOLSDIR:?}/sh-functions

compress=
case "${COMPRESS:-}" in
	gzip|gz)   compress='gzip'  ;;
	bzip2|bz2) compress='bzip2' ;;
	lzma)      compress='lzma'  ;;
	lzo)       compress='lzop'  ;;
	'')        compress=''      ;;
	*) fatal "Unknown compress method: $COMPRESS"
esac

if [ -n "$compress" ]; then
	$compress -9 < "$outfile" > "$outfile.x"
	mv -f -- "$outfile.x" "$outfile"
fi
