#!/bin/sh -eu

cd "$rootdir"

mkdir $verbose -p -- \
	./conf \
	./dev \
	./etc/modprobe.d \
	./etc/udev/rules.d \
	./"$kernel_modules_dir" \
	./lib/udev \
	./mnt \
	./root \
	./proc \
	./sys \
	./tmp \
	./var/lock \
	#

[ -e ./dev/ram     ] || mknod ./dev/ram	    b 1 1
[ -e ./dev/null    ] || mknod ./dev/null    c 1 3
[ -e ./dev/zero    ] || mknod ./dev/zero    c 1 5
[ -e ./dev/full    ] || mknod ./dev/full    c 1 7
[ -e ./dev/full    ] || mknod ./dev/random  c 1 8
[ -e ./dev/systty  ] || mknod ./dev/systty  c 4 0
[ -e ./dev/tty1    ] || mknod ./dev/tty1    c 4 1
[ -e ./dev/console ] || mknod ./dev/console c 5 1
[ -e ./dev/ptmx    ] || mknod ./dev/ptmx    c 5 2

cp $verbose -aLt . \
	"$datadir"/* \
	/lib/mkinitrd/klibc/* \
	/lib/mkinitrd/udev/* \
	/lib/mkinitrd/module-init-tools/* \
	#

[ ! -f /etc/modprobe.conf ] ||
	put-file /etc/modprobe.conf

[ ! -d /etc/modprobe.d ] ||
	find -L /etc/modprobe.d \
		\( \
			\! -name '*.rpm*' -a \
			\! -name '*~' \
		\) \
		-exec put-file '{}' '+'

[ ! -d /etc/udev/initramfs-rules.d ] ||
	find -L /etc/udev/initramfs-rules.d/ \
			-name '*.rules' \
		-exec cp $verbose -aLt ./etc/udev/rules.d -- '{}' '+'
