#!/bin/sh -eu

. sh-functions

cd "$rootdir"

mkdir $verbose -p -- \
	./.initrd/killall \
	./.initrd/uevent/events \
	./.initrd/uevent/queues/udev/.tmp \
	./dev \
	./etc/initrd \
	./etc/modprobe.d \
	./etc/sysconfig \
	./etc/udev/rules.d \
	./home/root \
	./"$kernel_modules_dir" \
	./lib/initrd \
	./lib/initrd/all \
	./lib/initrd/kmodules \
	./lib/initrd/post \
	./lib/initrd/pre \
	./lib/udev \
	./mnt \
	./root \
	./run \
	./proc \
	./sys \
	./tmp \
	./sbin \
	./var/lock/subsys \
	./var/log \
	./var/run \
	#

initrd-release

mkfifo ./.initrd/telinit
mkfifo ./.initrd/rdshell

which_args='--skip-alias --skip-functions --skip-dot --skip-tilde'
# shellcheck disable=SC2230
which="$(which $which_args which)"

UDEV_FILES='
	/sbin/udevd
	/sbin/udevadm
	/lib/udev/ata_id
	/lib/udev/cdrom_id
	/lib/udev/scsi_id'

UDEV_FILES_OLD='
	/lib/udev/edd_id
	/lib/udev/vol_id
	/lib/udev/path_id
	/lib/udev/usb_id
	/lib/udev/firmware'

PUT_FILES="${PUT_FILES-} $UDEV_FILES $(

printf '%s\n' \
	blkid cat chmod chroot cp depmod dmesg findmnt grep kill killall5 ln \
	logger ls lsmod mkdir mknod mktemp modprobe mount mountpoint mv \
	readlink rm rmdir runas setsid sh sleep start-stop-daemon switch_root \
	touch umount which ${PUT_FEATURE_PROGS-} ${PUT_PROGS-} |
	PATH="$BUSYBOX_PATH:$SYSTEM_PATH" xargs -r $which $which_args |
	sed -e 's#^/lib/initrd##';

for n in $UDEV_FILES_OLD /bin/shell-* /usr/share/terminfo/l /var/resolv; do
	[ ! -e "$n" ] || printf '%s\n' "$n"
done;
)"

[ -z "${LOCALBUILDDIR-}" ] ||
	PUT_DIRS="${PUT_DIRS-} ${LOCALBUILDDIR-}/lib/initrd"

PUT_DIRS="${PUT_DIRS-} $DATADIR /lib/initrd"

printf '%s\n' ${PUT_FEATURE_DIRS-} $PUT_DIRS   |sort -u |xargs -r put-tree .
printf '%s\n' ${PUT_FEATURE_FILES-} $PUT_FILES |sort -u |xargs -r put-file .

for i in rc0 rc1 rc2 rc3 rc4 rc5 rc6 init; do
	mkdir -p "./etc/rc.d/$i.d"
	ln -s -f "rc.d/$i.d" "./etc/$i.d"
done

for n in group gshadow passwd shadow fstab; do
	touch "./etc/$n"
done

# No shell access inside initramfs by default.
[ -s ./etc/sysconfig/rdshell ] ||
	printf 'RDSHELL_MODE=disable\n' >./etc/sysconfig/rdshell

if [ ! -x ./bin/sh ]; then
	for n in bash dash mksh ash; do
		[ -x "./bin/$n" ] || continue
		verbose "Setting $n as /bin/sh ..."
		ln -s "$n" ./bin/sh
		break
	done
fi

if [ -f /etc/modprobe.conf ]; then
	verbose "Copying /etc/modprobe.conf ..."
	put-file . /etc/modprobe.conf
fi

for d in lib etc; do
	if [ -d "/$d/modprobe.d" ]; then
		verbose "Copying files from $d/modprobe.d ..."
		find -L "/$d/modprobe.d" \
				-name '*.conf' \
			-exec cp -aLt ./etc/modprobe.d -- '{}' '+'
	fi

	if [ -d "/$d/udev/initramfs-rules.d" ]; then
		verbose "Copying files from /$d/udev/initramfs-rules.d ..."
		find -L "/$d/udev/initramfs-rules.d" \
				-name '*.rules' \
			-exec cp -aLt ./etc/udev/rules.d -- '{}' '+'
	fi
done

for n in builtin order builtin.modinfo; do
	[ ! -f "$kernel_modules_dir/modules.$n" ] ||
		cp -aLt ./"$kernel_modules_dir" -- "$kernel_modules_dir/modules.$n"
done
