#!/bin/bash -efu
# SPDX-License-Identifier: GPL-3.0-or-later

libc="$(
	ldd "$BASH" |
		sed -n -e 's|[[:space:]]*libc\.so.*[[:space:]]=>[[:space:]]\(/.*\)[[:space:]](0x.*$|\1|p'
)"
printf '%s\n' "${libc%/*}"
