#!/bin/sh -efu

. guess-functions

if [ -n "${RESOLVE_MODALIAS-}" ]; then
	while read -r alias; do
		resolve_modalias "$alias"
	done < "$guessdir/modalias" >> "$guessdir/modules"
	> "$guessdir/modalias"
fi

if [ -s "$guessdir/modules" -o -s "$guessdir/modalias" ]; then
	printf '%s\n' 'add-modules' >> "$guessdir/features"
fi

sort -uo "$guessdir/modules"  "$guessdir/modules"
sort -uo "$guessdir/modalias" "$guessdir/modalias"
sort -uo "$guessdir/features" "$guessdir/features"

printf 'MODULES_ADD\t+= '
while read n; do
	printf '%s ' "$n"
done < "$guessdir/modules"

while read n; do
	printf '%s ' "$n"
done < "$guessdir/modalias"
printf '\n'

printf 'FEATURES\t+= '
while read n; do
	printf '%s ' "$n"
done < "$guessdir/features"
printf '\n'
