#!/bin/sh -efu

. ${TOOLSDIR:?Tools directory required}/sh-functions
export PATH="$helpersdir:$PATH"

# TODO: Use gencpio

cd "$rootdir"

find . -mindepth 1 -print0 -o -prune |
	cpio -o0 -H newc --quiet > "$outfile"
