#!/bin/sh -eu

. ${TOOLSDIR:?Tools directory required}/sh-functions
export PATH="$helpersdir:$PATH"

for tree in "$@"; do
	verbose "Coping '$tree' recursively ..."
	cp -afLt "$rootdir" "$tree"/*
done
