#!/bin/bash -efu
# SPDX-License-Identifier: GPL-3.0-or-later

. sh-functions

destdir="$1"
shift

for tree in "$@"; do
	[ -d "$tree" ] || continue
	tree=$(readlink -ev "$tree")
	verbose "Copying '$tree' recursively ..."
	put-file -r "$tree" "$destdir" "$tree"
done
