#!/bin/sh -efu

. ${TOOLSDIR:?}/sh-functions

for elf in "$@"; do
	[ -e "$elf" ] ||
		fatal "$elf: No such file or directory"

	put-file "$elf"

	ldd -- "$elf" |sed -n 's/.*[[:space:]]\([^ ]\+\) (0x.*/\1/p' |
	while read fn; do
		put-file "$fn"
	done
done
