#!/bin/sh -efu

. ${TOOLSDIR:?}/sh-functions

put_program()
{
	local program="$1"
	local type="$(file -b "$program")" || fatal "Unable to get type of $program"

	helper=
	case "$type" in
		ELF\ *|*\ ELF\ *)
		helper="put-elf"
		;;
		Bourne\ shell\ script\ *)
		#FIXME: process shell scripts more careful
		helper="put-file"
		;;
		*)
		fatal "Unexpected file type of $program: $type"
	esac

	"$helper" $1
}

for p in "$@"; do
	put_program "$p"
done
