#!/bin/sh -efu

. sh-functions

cd "$rootdir"

mkdir -p -- ./etc

while IFS=: read -r name pass gid dummy; do
	[ -n "$name" ] && [ "$gid" -lt 500 ] ||
		continue
	printf '%s\n' "$name:x:$gid:$dummy" >> ./etc/group
	printf '%s\n' "$name:x::$dummy" >> ./etc/gshadow
done < /etc/group

while IFS=: read -r name pass uid gid dummy; do
	[ -n "$name" ] && [ "$uid" -lt 500 ] ||
		continue
	{
		[ "$name" = "root" ] &&
			printf '%s\n' "root:x:$uid:$gid::/home/root:/bin/sh" ||
			printf '%s\n' "$name:x:$uid:$gid:$dummy"
	} >> ./etc/passwd
	printf '%s\n' "$name:*:13957::::::" >> ./etc/shadow
done < /etc/passwd
