#!/bin/sh -efu

. shell-error

which_args='--skip-alias --skip-functions --skip-dot --skip-tilde'
# shellcheck disable=SC2230
which="$(which $which_args which)"

udevd_binary()
{
	local udevd
	udevd="$($which $which_args udevd)" ||
		return 0
	"$udevd" --version
}

udevadm_binary()
{
	local udevadm
	udevadm="$($which $which_args udevadm)" ||
		return 0
	"$udevadm" --version
}

v="$(udevd_binary --version)"
[ -n "${v##*[!0-9]*}" ] || v="$(udevadm_binary --version)"
[ -n "${v##*[!0-9]*}" ] || v="0"

echo "$v"
