MODULES_PRELOAD	+= $(MULTIPATH_PRELOAD)

MULTIPATH_PATTERN_SET = name:^scsi_dh
MODULES_PATTERN_SETS += MULTIPATH_PATTERN_SET

PUT_FEATURE_FILES += $(MULTIPATH_BIN) $(MULTIPATH_CONF) $(MULTIPATH_DATA)

$(call require,devmapper)
$(call require,depmod-image)
