# SPDX-License-Identifier: GPL-3.0-or-later
MODULES_PRELOAD	+= $(MULTIPATH_PRELOAD)

MULTIPATH_PATTERN_SET = name:^scsi_dh
MODULES_PATTERN_SETS += MULTIPATH_PATTERN_SET

PUT_UDEV_RULES += $(MULTIPATH_RULES)

PUT_FEATURE_FILES += $(MULTIPATH_CONF)
PUT_FEATURE_DIRS  += $(MULTIPATH_DATADIR)
PUT_FEATURE_PROGS += $(MULTIPATH_PROGS)
PUT_FEATURE_FILES += $(MULTIPATH_FILES)
