#!/bin/sh

msg=
run() {
	[ ! -s /etc/initrd/initramfs.conf ] || . /etc/initrd/initramfs.conf

	export PATH=/bin:/sbin:/usr/bin:/usr/sbin
	export RUN_INITRD=1
	export INIT='/sbin/init'
	export DEBUG=
	export QUIET=
	export PANIC=
	export STOP=','
	export IGNORE=','
	export rootmnt='/root'
	export omitproc='/dev/.initramfs/omitproc'
	export udev_eventdir='/dev/.initramfs/udev-events'
	export handler_eventdir='/dev/.initramfs/handler-events'
	export readonly=1
	export RESCUE_MODULES="${RESCUE_MODULES-}"
	export UDEV_VERSION="$(udevd --version)" ||:

	export RD_TIMESTAMP=0
}
