#!/bin/sh

msg='Stopping udevd...'
run() {
	# Stop udevd, we'll miss a few events while we run init, but we catch up
	udevadm settle
	udevadm control --stop-exec-queue
	udevadm control --exit

	# ignore any failed event because the init script will trigger again all events
	udevadm info --cleanup-db
}
