#!/bin/sh

. /scripts/functions

handler() {
	[ -d "$MOUNTPOINT" ] ||
		return 1
	mountpoint -q "$MOUNTPOINT" ||
		mount ${DEBUG:+-v} "$roflag" "$MOUNTPOINT" ||
		return 1
}

roflag=-w
[ -z "$readonly" ] || roflag=-r

for e in "$handler_eventdir"/mountdev.*; do
	( . "$e"; handler; ) && done_event "$e" ||:
done
