#!/bin/bash -efu
# SPDX-License-Identifier: GPL-3.0-or-later

[ -d "$SYSFS_PATH$1"/dm ] ||
	exit 0

. guess-functions

uuid=
readline uuid "$SYSFS_PATH$1"/dm/uuid

[ -n "$uuid" ] ||
	exit 0

[ -n "${uuid##LVM-*}" ] ||
	guess_feature lvm
