#!/bin/bash -efu
# SPDX-License-Identifier: GPL-3.0-or-later

. guess-functions

if [ -f "$KERNEL_CONFIG" ]; then
	grep -qs "^CONFIG_BOOT_CONFIG=y" "$KERNEL_CONFIG" ||
		exit 0
fi

if [ -z "${BOOT_CONFIG-}" ]; then
	[ -s "$PROCFS_PATH/bootconfig" ] ||
		exit 0

	BOOT_CONFIG="$PROCFS_PATH/bootconfig"

	guess_variable BOOT_CONFIG "$BOOT_CONFIG"
fi

[ -s "$BOOT_CONFIG" ] ||
	exit 0

guess_feature "bootconfig"
