#!/bin/sh -efu

. /.initrd/initenv
. uevent-sh-functions
. initrd-sh-functions

eof=
while [ -z "$eof" ]; do
	read fsdev fsdir dummy ||
		eof=1
	[ -n "$fsdev" ] ||
		continue

	if [ -n "${ROOTONLY-}" ]; then
		[ "$fsdir" = "$rootmnt/" ] ||
			continue
	fi

	dev=
	get_dev dev "$fsdev" ||
		continue

	event="$(make_event)"

	cat > "$event" <<-EOF
		MOUNTDEV="$dev"
		MOUNTPOINT="$fsdir"
	EOF

	release_event mountdev "$event"
done < /etc/fstab
