#!/bin/bash -efu

. /.initrd/initenv
. uevent-sh-functions
. initrd-sh-functions

eof=
while [ -z "$eof" ]; do
	read -r fsdev fsdir fstype fsopts freq passno ||
		eof=1
	[ -n "$fsdev" ] ||
		continue

	if [ -n "${ROOTONLY-}" ]; then
		[ "$fsdir" = "$rootmnt" ] ||
			continue
	fi

	dev=
	if [ -n "${fsopts##*,x-initrd-mount-source}" ]; then
		get_dev dev "$fsdev" ||
			continue
	else
		dev="$fsdev"
	fi

	event="$(make_event)"

	cat > "$event" <<-EOF
		MOUNTDEV="$dev"
		MOUNTPOINT="$fsdir"
	EOF

	release_event mountdev "$event"
done < /etc/fstab
