#!/bin/sh -e

. /.initrd/initenv
. uevent-sh-functions

if [ -z "$IP" ] || [ "$IP" = 0 ]; then
	# Special case for nfsroot.
	if [ -n "$NFSROOT" -o "$ROOT" = '/dev/nfs' ]; then
		export IP0=dhcp
		export IP=1
	fi
fi

[ -n "$IP" ] && [ "$IP" != 0 ] ||
	exit 0

if [ "$INTERFACE" = 'lo' ]; then
	iface=
	i=0
	while [ "$iface" != 'lo' ] && [ $i -lt $IP ]; do
		eval "IPOPTS=\"\$IP$i\""
		iface="${IPOPTS%:*}"
		iface="${iface##*:}"
		i=$(($i+1))
	done

	if [ "$iface" != 'lo' ]; then
		export IP0=127.0.0.1:::::lo:none
		export IP=1
	fi
fi


event="$(make_event)"
showenv -q > "$event"
release_event netdev "$event"
