#!/bin/bash -eu
# SPDX-License-Identifier: GPL-3.0-or-later

export LANG=C
export LC_ALL=C

cwd="$(readlink -ev "$0")"
cwd="${cwd%/*}"

ret=0
for testsuite in "$@"; do
	[ -d "$testsuite" ] ||
		continue

	name="${testsuite%/tests}"
	name="${name}"

	testsuite="$PWD/$testsuite"
	max=$(find "$testsuite" -type d -name 'ts*' | wc -l)

	echo "=== Check $name [$max]";

	i=1
	for ts in "$testsuite"/ts*; do
		[ -d "$ts" ] ||
			continue

		if [ -n "${VERBOSE:-${V:-}}" ]; then
			num="$(printf '%4s' "$i")"
			i=$(( $i + 1 ))

			echo "[$num/$max] ${ts##*/}"
		fi

		{
			rc=0
			"$ts"/run || rc=$?
			echo "rc=$rc";
		} > "$ts"/output 2>&1

		[ ! -f "$ts"/expect.in ] ||
			sed \
			-e "s#@ts@#${ts##*/}#g" \
			-e "s#@cwd@#$testsuite#g" \
			< "$ts"/expect.in > "$ts"/expect

		if ! cmp -s "$ts"/expect "$ts"/output; then
			echo "!!! Test ${ts##*/} failed:"
			diff -u -- "$ts"/expect "$ts"/output ||:
			[ -e "$ts/known-failure" ] ||
				ret=1
		else
			rm -f -- "$ts"/output
		fi

		[ ! -f "$ts"/expect.in ] ||
			rm -f -- "$ts"/expect
	done
done

exit "$ret"
