# SPDX-License-Identifier: GPL-3.0-or-later

# squashfs or erofs
RUNTIME_BASE_LAYER ?=

RUNTIME_LAYER_EROFS_ARGS ?=
RUNTIME_LAYER_EROFS_COMPRESS ?=

RUNTIME_LAYER_SQUASHFS_ARGS ?= -b 1M
RUNTIME_LAYER_SQUASHFS_COMPRESS ?= xz
