#!/bin/sh

. /scripts/functions

quiet=${1:+:}
doexit() {
	$quiet error "$1"
	exit 1
}

eof=
while [ -z "$eof" ]; do
	read fsdev fsdir dummy ||
		eof=1

	[ -n "$fsdev" ] ||
		continue

	if [ -n "${ROOTONLY-}" ]; then
		[ "$fsdir" = "$rootmnt/" ] ||
			continue
	fi

	[ -d "$fsdir" ] ||
		doexit "$fsdir: Does not exist"

	mountpoint -q "$fsdir" ||
		doexit "$fsdir: Not mounted"

done < /etc/fstab
